In [ ]:
import random
import time
from collections import OrderedDict
from copy import deepcopy
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import h5py
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.io as sio
import seaborn as sns
import torch
import torch.nn as nn
import torch.optim as optim
from IPython.display import display
from torch.utils.data import DataLoader, Dataset, Subset
from tqdm.auto import tqdm

sns.set_theme(style='whitegrid')
pd.set_option('display.max_columns', None)
try:
    torch.set_float32_matmul_precision('high')
except AttributeError:
    pass


@dataclass(frozen=True)
class Config:
    # ==============================
    # Required hyperparameters
    # ==============================
    NUM_CLIENTS: int = 20
    BUDGET: float = 100.0
    GLOBAL_ROUNDS: int = 100
    LOCAL_EPOCHS: int = 2
    BATCH_SIZE: int = 32
    LR: float = 0.01
    MC_ITERATIONS: int = 10

    # ==============================
    # Benchmark and runtime settings
    # ==============================
    DIRICHLET_ALPHA: float = 0.5
    VAL_RATIO: float = 0.10
    RANDOM_SEED: int = 42
    DATA_DIR: str = './data'
    DIGITS_FILE: str = 'emnist-digits.mat'
    LETTERS_FILE: str = 'emnist-letters.mat'
    INITIAL_REPUTATION: float = 5.0
    REPUTATION_REWARD: float = 0.5
    REPUTATION_PENALTY: float = 2.0
    HACKER_RATIO: float = 0.20
    BID_ATTACK_RATIO: float = 0.30
    BID_ATTACK_MULTIPLIER: float = 2.40
    NUM_CLASSES_DIGITS: int = 10
    NUM_CLASSES_LETTERS: int = 26
    NUM_WORKERS: int = 0
    MC_VAL_SUBSET_SIZE: Optional[int] = 4000
    MAX_TRAIN_SAMPLES: Optional[int] = None
    MAX_VAL_SAMPLES: Optional[int] = None
    LOG_EVERY: int = 1
    CONVERGENCE_RATIO: float = 0.95

    @property
    def NUM_CLASSES(self) -> int:
        return self.NUM_CLASSES_DIGITS + self.NUM_CLASSES_LETTERS


cfg = Config()
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def ensure_data_files(config: Config) -> Tuple[Path, Path]:
    # This function supports both local execution and Google Colab.
    data_dir = Path(config.DATA_DIR)
    data_dir.mkdir(parents=True, exist_ok=True)

    digits_path = data_dir / config.DIGITS_FILE
    letters_path = data_dir / config.LETTERS_FILE

    if digits_path.exists() and letters_path.exists():
        print(f'Found dataset files at: {data_dir.resolve()}')
        return digits_path, letters_path

    print('Dataset files were not found. If you are using Colab, upload both .mat files now.')
    try:
        from google.colab import files

        uploaded = files.upload()
        for filename, content in uploaded.items():
            target_path = data_dir / Path(filename).name
            with open(target_path, 'wb') as file_obj:
                file_obj.write(content)
    except ImportError:
        print('This environment is not Google Colab. Please place the files under ./data before running.')

    missing_files = [
        path.name
        for path in (digits_path, letters_path)
        if not path.exists()
    ]
    if missing_files:
        raise FileNotFoundError(
            'Missing dataset files: '
            + ', '.join(missing_files)
            + '. Please upload them to the data/ directory.'
        )

    return digits_path, letters_path


set_seed(cfg.RANDOM_SEED)
digits_path, letters_path = ensure_data_files(cfg)
print(f'Running on device: {device}')
print(f'Total number of classes after merging digits + letters: {cfg.NUM_CLASSES}')

Dataset files were not found. If you are using Colab, upload both .mat files now.

Saving emnist-digits.mat to emnist-digits.mat
Saving emnist-letters.mat to emnist-letters.mat
Running on device: cuda
Total number of classes after merging digits + letters: 36

In [ ]:
IMAGE_KEYS = {'images', 'image', 'x', 'data'}
LABEL_KEYS = {'labels', 'label', 'y', 'target', 'targets'}
CLASS_NAMES = [str(index) for index in range(cfg.NUM_CLASSES_DIGITS)] + [chr(ord('A') + index) for index in range(cfg.NUM_CLASSES_LETTERS)]


def matlab_to_python(obj: Any) -> Any:
    # Recursively convert MATLAB structs into Python-native objects.
    if hasattr(obj, '_fieldnames'):
        return {
            field: matlab_to_python(getattr(obj, field))
            for field in obj._fieldnames
        }
    if isinstance(obj, np.ndarray):
        if obj.dtype == object:
            return [matlab_to_python(item) for item in obj.flat]
        return obj
    if isinstance(obj, list):
        return [matlab_to_python(item) for item in obj]
    if isinstance(obj, tuple):
        return tuple(matlab_to_python(item) for item in obj)
    return obj


def h5_to_python(node: Any, file_obj: h5py.File) -> Any:
    # Fallback loader for MAT files that behave like HDF5 containers.
    if isinstance(node, h5py.Group):
        return {
            key: h5_to_python(node[key], file_obj)
            for key in node.keys()
        }
    if isinstance(node, h5py.Dataset):
        data = node[()]
        ref_dtype = h5py.check_dtype(ref=node.dtype)
        if ref_dtype is not None:
            refs = np.array(data).flatten().tolist()
            return [h5_to_python(file_obj[ref], file_obj) for ref in refs]
        return np.array(data)
    return node


def load_mat_file(mat_path: Path) -> Dict[str, Any]:
    try:
        raw_data = sio.loadmat(mat_path, squeeze_me=True, struct_as_record=False)
        return {
            key: matlab_to_python(value)
            for key, value in raw_data.items()
            if not key.startswith('__')
        }
    except NotImplementedError:
        with h5py.File(mat_path, 'r') as file_obj:
            return {
                key: h5_to_python(file_obj[key], file_obj)
                for key in file_obj.keys()
            }


def standardize_images(images: Any) -> np.ndarray:
    # Convert images into [N, 1, 28, 28] with uint8 dtype to save memory.
    image_array = np.asarray(images)
    image_array = np.squeeze(image_array)

    if image_array.ndim == 2:
        if image_array.shape[1] == 28 * 28:
            image_array = image_array.reshape(-1, 28, 28)
        elif image_array.shape[0] == 28 * 28:
            image_array = image_array.T.reshape(-1, 28, 28)
        else:
            raise ValueError(f'Unsupported 2D image shape: {image_array.shape}')
    elif image_array.ndim == 3:
        if image_array.shape[0] == 28 and image_array.shape[1] == 28:
            image_array = np.transpose(image_array, (2, 0, 1))
        elif image_array.shape[1] == 28 and image_array.shape[2] == 28:
            pass
        elif image_array.shape[0] == 28 and image_array.shape[2] == 28:
            image_array = np.transpose(image_array, (1, 0, 2))
        else:
            raise ValueError(f'Unsupported 3D image shape: {image_array.shape}')
    else:
        raise ValueError(f'Unsupported image rank: {image_array.ndim}')

    image_array = image_array.astype(np.float32)
    if image_array.max() <= 1.0:
        image_array = image_array * 255.0
    image_array = np.clip(image_array, 0, 255).astype(np.uint8)
    return image_array[:, None, :, :]


def standardize_labels(labels: Any, expected_num_classes: int) -> np.ndarray:
    # Convert labels into a 1D zero-based integer vector.
    label_array = np.asarray(labels).reshape(-1).astype(np.int64)

    min_label = int(label_array.min())
    max_label = int(label_array.max())
    if min_label == 1 and max_label == expected_num_classes:
        label_array = label_array - 1
    elif min_label != 0:
        label_array = label_array - min_label

    return label_array


def find_image_label_pairs(node: Any, path: str = 'root') -> List[Dict[str, Any]]:
    # Traverse the full object tree and extract valid (images, labels) pairs.
    pairs: List[Dict[str, Any]] = []

    if isinstance(node, dict):
        lowered = {str(key).lower(): value for key, value in node.items()}
        image_key = next((key for key in lowered if key in IMAGE_KEYS), None)
        label_key = next((key for key in lowered if key in LABEL_KEYS), None)

        if image_key is not None and label_key is not None:
            pairs.append(
                {
                    'path': path,
                    'images': lowered[image_key],
                    'labels': lowered[label_key],
                }
            )

        for key, value in node.items():
            pairs.extend(find_image_label_pairs(value, f'{path}.{key}'))
    elif isinstance(node, (list, tuple)):
        for index, value in enumerate(node):
            pairs.extend(find_image_label_pairs(value, f'{path}[{index}]'))

    return pairs


def load_emnist_subset(
    mat_path: Path,
    expected_num_classes: int,
    label_offset: int = 0,
) -> Tuple[np.ndarray, np.ndarray]:
    raw_data = load_mat_file(mat_path)
    candidate_pairs = find_image_label_pairs(raw_data)

    valid_pairs = []
    seen_signatures = set()
    for pair in candidate_pairs:
        try:
            images = standardize_images(pair['images'])
            labels = standardize_labels(pair['labels'], expected_num_classes)
        except Exception:
            continue

        if len(images) != len(labels):
            continue

        label_signature = int(labels[: min(256, len(labels))].sum())
        image_signature = int(images[:1].sum())
        signature = (
            images.shape,
            image_signature,
            len(labels),
            int(labels.min()),
            int(labels.max()),
            label_signature,
        )
        if signature in seen_signatures:
            continue

        seen_signatures.add(signature)
        valid_pairs.append({'path': pair['path'], 'images': images, 'labels': labels})

    if not valid_pairs:
        raise ValueError(f'Could not extract a valid dataset from {mat_path.name}')

    print(f'[{mat_path.name}] Detected {len(valid_pairs)} valid splits:')
    for pair in valid_pairs:
        print(f"  - {pair['path']}: {len(pair['labels'])} samples")

    all_images = np.concatenate([pair['images'] for pair in valid_pairs], axis=0)
    all_labels = np.concatenate([pair['labels'] for pair in valid_pairs], axis=0) + label_offset
    return all_images, all_labels


digits_images, digits_labels = load_emnist_subset(
    digits_path,
    expected_num_classes=cfg.NUM_CLASSES_DIGITS,
    label_offset=0,
)
letters_images, letters_labels = load_emnist_subset(
    letters_path,
    expected_num_classes=cfg.NUM_CLASSES_LETTERS,
    label_offset=cfg.NUM_CLASSES_DIGITS,
)

all_images = np.concatenate([digits_images, letters_images], axis=0)
all_labels = np.concatenate([digits_labels, letters_labels], axis=0)

print(f'Total samples after merging: {len(all_labels):,}')
print(f'Image tensor shape: {all_images.shape}')
print(f'Label range: [{all_labels.min()} - {all_labels.max()}]')

[emnist-digits.mat] Detected 2 valid splits:
  - root.dataset.train: 240000 samples
  - root.dataset.test: 40000 samples
[emnist-letters.mat] Detected 2 valid splits:
  - root.dataset.train: 124800 samples
  - root.dataset.test: 20800 samples
Total samples after merging: 425,600
Image tensor shape: (425600, 1, 28, 28)
Label range: [0 - 35]

In [ ]:
class EMNISTDataset(Dataset):
    # Lightweight dataset wrapper that converts images to float only inside __getitem__.
    def __init__(self, images: np.ndarray, labels: np.ndarray) -> None:
        self.images = torch.from_numpy(images)
        self.labels = torch.from_numpy(labels.astype(np.int64))

    def __len__(self) -> int:
        return len(self.labels)

    def __getitem__(self, index: int) -> Tuple[torch.Tensor, torch.Tensor]:
        image = self.images[index].float() / 255.0
        label = self.labels[index].long()
        return image, label


def maybe_limit_indices(indices: np.ndarray, max_samples: Optional[int], seed: int) -> np.ndarray:
    if max_samples is None or len(indices) <= max_samples:
        return indices
    rng = np.random.default_rng(seed)
    return np.sort(rng.choice(indices, size=max_samples, replace=False))


def train_val_split_indices(total_size: int, val_ratio: float, seed: int) -> Tuple[np.ndarray, np.ndarray]:
    rng = np.random.default_rng(seed)
    indices = np.arange(total_size)
    rng.shuffle(indices)
    val_size = int(total_size * val_ratio)
    val_indices = indices[:val_size]
    train_indices = indices[val_size:]
    return train_indices, val_indices


def dirichlet_split_noniid(
    labels: np.ndarray,
    num_clients: int,
    alpha: float,
    min_size: int,
    seed: int,
) -> List[np.ndarray]:
    # Split data using a Dirichlet distribution to create realistic non-IID client partitions.
    unique_classes = np.unique(labels)
    rng = np.random.default_rng(seed)
    min_partition_size = 0

    while min_partition_size < min_size:
        client_relative_indices = [[] for _ in range(num_clients)]

        for class_id in unique_classes:
            class_indices = np.where(labels == class_id)[0]
            rng.shuffle(class_indices)

            proportions = rng.dirichlet(np.repeat(alpha, num_clients))
            split_points = (np.cumsum(proportions)[:-1] * len(class_indices)).astype(int)
            class_chunks = np.split(class_indices, split_points)

            for client_id, chunk in enumerate(class_chunks):
                client_relative_indices[client_id].extend(chunk.tolist())

        min_partition_size = min(len(indices) for indices in client_relative_indices)

    return [np.array(indices, dtype=np.int64) for indices in client_relative_indices]


def summarize_client_distribution(labels: np.ndarray, relative_indices: np.ndarray, top_k: int = 3) -> str:
    unique_labels, counts = np.unique(labels[relative_indices], return_counts=True)
    top_pairs = sorted(
        zip(unique_labels.tolist(), counts.tolist()),
        key=lambda item: item[1],
        reverse=True,
    )[:top_k]
    return ', '.join(f'{CLASS_NAMES[class_id]}: {count}' for class_id, count in top_pairs)


def build_client_partitions(
    labels: np.ndarray,
    train_indices: np.ndarray,
    config: Config,
) -> Tuple[Dict[int, np.ndarray], pd.DataFrame, np.ndarray]:
    train_labels = labels[train_indices]
    client_relative_splits = dirichlet_split_noniid(
        labels=train_labels,
        num_clients=config.NUM_CLIENTS,
        alpha=config.DIRICHLET_ALPHA,
        min_size=config.BATCH_SIZE,
        seed=config.RANDOM_SEED,
    )

    client_index_map: Dict[int, np.ndarray] = {}
    summary_rows = []
    client_class_matrix = np.zeros((config.NUM_CLIENTS, config.NUM_CLASSES), dtype=np.int64)

    for client_id, relative_indices in enumerate(client_relative_splits):
        absolute_indices = train_indices[relative_indices]
        client_index_map[client_id] = absolute_indices

        local_labels = labels[absolute_indices]
        client_class_matrix[client_id] = np.bincount(local_labels, minlength=config.NUM_CLASSES)
        summary_rows.append(
            {
                'Client ID': client_id,
                'Num Samples': len(absolute_indices),
                'Top Classes': summarize_client_distribution(train_labels, relative_indices),
            }
        )

    return client_index_map, pd.DataFrame(summary_rows), client_class_matrix


def build_client_loaders(
    dataset: Dataset,
    client_index_map: Dict[int, np.ndarray],
    config: Config,
) -> Dict[int, DataLoader]:
    client_loaders: Dict[int, DataLoader] = {}
    for client_id, absolute_indices in client_index_map.items():
        subset = Subset(dataset, absolute_indices.tolist())
        client_loaders[client_id] = DataLoader(
            subset,
            batch_size=config.BATCH_SIZE,
            shuffle=True,
            num_workers=config.NUM_WORKERS,
            pin_memory=device.type == 'cuda',
        )
    return client_loaders


full_dataset = EMNISTDataset(all_images, all_labels)
train_indices, val_indices = train_val_split_indices(len(full_dataset), cfg.VAL_RATIO, cfg.RANDOM_SEED)
train_indices = maybe_limit_indices(train_indices, cfg.MAX_TRAIN_SAMPLES, cfg.RANDOM_SEED)
val_cap = cfg.MC_VAL_SUBSET_SIZE if cfg.MAX_VAL_SAMPLES is None else min(cfg.MAX_VAL_SAMPLES, cfg.MC_VAL_SUBSET_SIZE or cfg.MAX_VAL_SAMPLES)
val_indices = maybe_limit_indices(val_indices, val_cap, cfg.RANDOM_SEED + 1)

client_index_map, client_distribution_df, client_class_matrix = build_client_partitions(
    labels=all_labels,
    train_indices=train_indices,
    config=cfg,
)
client_loaders = build_client_loaders(full_dataset, client_index_map, cfg)
val_loader = DataLoader(
    Subset(full_dataset, val_indices.tolist()),
    batch_size=cfg.BATCH_SIZE,
    shuffle=False,
    num_workers=cfg.NUM_WORKERS,
    pin_memory=device.type == 'cuda',
)

print(f'Federated training samples: {len(train_indices):,}')
print(f'Central validation samples: {len(val_indices):,}')
display(client_distribution_df)

Federated training samples: 383,040
Central validation samples: 4,000

    Client ID  Num Samples                Top Classes
0           0        18060  3: 3391, 9: 2498, 0: 1355
1           1        18394  0: 5694, 3: 2965, 1: 1713
2           2        15017  9: 4539, 5: 3593, Y: 1320
3           3        18394  9: 5921, 6: 1627, 1: 1195
4           4        24264  3: 4352, 5: 3087, 0: 2472
5           5        22136  2: 5685, 9: 4499, 7: 2390
6           6        13839  2: 2267, 3: 1932, 6: 1858
7           7        18801   1: 7078, 7: 4068, 5: 961
8           8        24118  6: 4647, 7: 4128, 5: 3546
9           9        26275  4: 5425, 0: 4606, 2: 2401
10         10        12128  2: 2088, 9: 1919, 0: 1843
11         11         8617     1: 957, E: 952, K: 638
12         12        21638  8: 8734, 7: 1824, 5: 1454
13         13        21007  5: 4147, 4: 3029, 8: 2663
14         14        27490  3: 5794, 2: 4912, 6: 4250
15         15        29072  1: 8754, 4: 3996, 7: 3086
16         16         8966   8: 2462, N: 1264, G: 975
17         17        19759  8: 3554, 4: 3327, 7: 2562
18         18        21278  0: 2335, 6: 1975, 2: 1772
19         19        13787  X: 1443, 0: 1429, B: 1255

In [ ]:
class SimpleCNN(nn.Module):
    # A compact CNN with 2 Conv2d blocks, MaxPool layers, and 2 Linear layers.
    def __init__(self, num_classes: int) -> None:
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=2, stride=2),
        )
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(64 * 7 * 7, 128),
            nn.ReLU(inplace=True),
            nn.Linear(128, num_classes),
        )

    def forward(self, inputs: torch.Tensor) -> torch.Tensor:
        features = self.features(inputs)
        return self.classifier(features)


def clone_state_dict(state_dict: Dict[str, torch.Tensor]) -> OrderedDict:
    return OrderedDict(
        (key, value.detach().cpu().clone())
        for key, value in state_dict.items()
    )


def fedavg_state_dicts(weighted_states: List[Tuple[Dict[str, torch.Tensor], int]]) -> OrderedDict:
    # Weighted FedAvg aggregation by local sample count.
    if not weighted_states:
        raise ValueError('weighted_states must not be empty.')

    total_samples = sum(num_samples for _, num_samples in weighted_states)
    averaged_state = OrderedDict()
    for key in weighted_states[0][0].keys():
        weighted_sum = sum(
            state_dict[key].float() * (num_samples / total_samples)
            for state_dict, num_samples in weighted_states
        )
        averaged_state[key] = weighted_sum.clone()
    return averaged_state


def compute_model_size_mb(model: nn.Module) -> float:
    total_bytes = sum(tensor.numel() * tensor.element_size() for tensor in model.state_dict().values())
    return total_bytes / (1024 ** 2)


@torch.inference_mode()
def evaluate_model(
    model: nn.Module,
    dataloader: DataLoader,
    device: torch.device,
    num_classes: int,
    return_confusion: bool = False,
):
    model.eval()
    correct_predictions = 0
    total_samples = 0
    confusion_matrix = np.zeros((num_classes, num_classes), dtype=np.int64) if return_confusion else None

    for images, labels in dataloader:
        images = images.to(device)
        labels = labels.to(device)
        logits = model(images)
        predictions = logits.argmax(dim=1)

        correct_predictions += (predictions == labels).sum().item()
        total_samples += labels.size(0)

        if confusion_matrix is not None:
            for true_label, pred_label in zip(labels.cpu().numpy(), predictions.cpu().numpy()):
                confusion_matrix[int(true_label), int(pred_label)] += 1

    accuracy = correct_predictions / max(total_samples, 1)
    if return_confusion:
        return accuracy, confusion_matrix
    return accuracy


def estimate_convergence_round(history: List[float], ratio: float) -> int:
    if not history:
        return 0
    target_accuracy = max(history) * ratio
    for round_index, accuracy in enumerate(history, start=1):
        if accuracy >= target_accuracy:
            return round_index
    return len(history)


def scenario_label(scenario) -> str:
    return f"{scenario.scenario_id} | {scenario.title}"

In [ ]:
@dataclass(frozen=True)
class ScenarioSpec:
    scenario_id: str
    title: str
    case_name: str
    mechanism: str
    attack_mode: str
    description: str


@dataclass(frozen=True)
class ClientBlueprint:
    client_id: int
    true_cost: float
    truthful_bid: float
    manipulated_bid: float
    is_bid_attacker: bool
    is_hacker: bool


class Client:
    def __init__(
        self,
        client_id: int,
        true_cost: float,
        truthful_bid: float,
        bid_price: float,
        config: Config,
        device: torch.device,
        is_hacker: bool = False,
        is_bid_attacker: bool = False,
    ) -> None:
        self.id = client_id
        self.true_cost = true_cost
        self.truthful_bid = truthful_bid
        self.bid_price = bid_price
        self.reputation = config.INITIAL_REPUTATION
        self.is_hacker = is_hacker
        self.is_bid_attacker = is_bid_attacker
        self.config = config
        self.device = device
        self.total_payment = 0.0
        self.last_payment = 0.0
        self.selected_rounds = 0
        self.accepted_rounds = 0

    def local_train(self, global_model: nn.Module, dataloader: DataLoader) -> Dict[str, Any]:
        # Each client receives the global model, trains locally, and returns a new state_dict.
        local_model = deepcopy(global_model).to(self.device)
        local_model.train()

        criterion = nn.CrossEntropyLoss()
        optimizer = optim.SGD(local_model.parameters(), lr=self.config.LR, momentum=0.9)

        for _ in range(self.config.LOCAL_EPOCHS):
            for images, labels in dataloader:
                images = images.to(self.device)
                labels = labels.to(self.device)

                # Malicious clients use label flipping to corrupt their local update.
                if self.is_hacker:
                    labels = (labels + 1) % self.config.NUM_CLASSES

                optimizer.zero_grad()
                logits = local_model(images)
                loss = criterion(logits, labels)
                loss.backward()
                optimizer.step()

        return {
            'weights': clone_state_dict(local_model.state_dict()),
            'num_samples': len(dataloader.dataset),
        }


class VanillaSelectionCore:
    def __init__(self, budget: float, seed: int) -> None:
        self.budget = budget
        self.seed = seed

    def select_clients(self, clients: List[Client], round_idx: int) -> Tuple[List[Client], float]:
        # Baseline selection: random ready-order under a hard budget constraint.
        round_rng = random.Random(self.seed + round_idx)
        candidate_clients = clients.copy()
        round_rng.shuffle(candidate_clients)

        selected_clients: List[Client] = []
        spent_budget = 0.0
        for client in candidate_clients:
            if spent_budget + client.bid_price <= self.budget:
                selected_clients.append(client)
                spent_budget += client.bid_price
        return selected_clients, spent_budget


class EconomicCore:
    def __init__(self, budget: float) -> None:
        self.budget = budget

    def select_clients(
        self,
        clients: List[Client],
    ) -> Tuple[List[Client], Dict[int, float], Optional[Client], float]:
        # Myerson-style economic score: s_i = reputation / bid_price.
        ranked_clients = sorted(
            clients,
            key=lambda client: client.reputation / max(client.bid_price, 1e-8),
            reverse=True,
        )

        selected_clients: List[Client] = []
        first_loser: Optional[Client] = None
        spent_budget = 0.0

        for client in ranked_clients:
            if spent_budget + client.bid_price <= self.budget:
                selected_clients.append(client)
                spent_budget += client.bid_price
            elif first_loser is None:
                first_loser = client

        if not selected_clients:
            return [], {}, first_loser, spent_budget

        if first_loser is None:
            first_loser = selected_clients[-1]

        critical_ratio = first_loser.bid_price / max(first_loser.reputation, 1e-8)
        payments = {
            client.id: client.reputation * critical_ratio
            for client in selected_clients
        }
        return selected_clients, payments, first_loser, spent_budget


class SecurityCore:
    def __init__(
        self,
        model_factory,
        val_loader: DataLoader,
        device: torch.device,
        mc_iterations: int,
        num_classes: int,
    ) -> None:
        self.model_factory = model_factory
        self.val_loader = val_loader
        self.device = device
        self.mc_iterations = mc_iterations
        self.num_classes = num_classes
        self.accuracy_cache: Dict[Tuple[int, ...], float] = {}

    def _build_model(self) -> nn.Module:
        return self.model_factory().to(self.device)

    def evaluate(self, model: nn.Module) -> float:
        return evaluate_model(model, self.val_loader, self.device, self.num_classes)

    def _evaluate_state_dict(self, state_dict: Dict[str, torch.Tensor]) -> float:
        model = self._build_model()
        model.load_state_dict(state_dict)
        return self.evaluate(model)

    def _subset_accuracy(
        self,
        subset_ids: Tuple[int, ...],
        base_model_state: Dict[str, torch.Tensor],
        local_updates: Dict[int, Dict[str, Any]],
    ) -> float:
        # Cache subset evaluations to avoid recomputing the same merged model.
        sorted_subset = tuple(sorted(subset_ids))
        if sorted_subset in self.accuracy_cache:
            return self.accuracy_cache[sorted_subset]

        if not sorted_subset:
            accuracy = self._evaluate_state_dict(base_model_state)
        else:
            aggregated_state = fedavg_state_dicts(
                [
                    (local_updates[client_id]['weights'], local_updates[client_id]['num_samples'])
                    for client_id in sorted_subset
                ]
            )
            accuracy = self._evaluate_state_dict(aggregated_state)

        self.accuracy_cache[sorted_subset] = accuracy
        return accuracy

    def mc_sva(
        self,
        base_model_state: Dict[str, torch.Tensor],
        local_updates: Dict[int, Dict[str, Any]],
    ) -> Dict[int, float]:
        client_ids = list(local_updates.keys())
        shapley_scores = {client_id: 0.0 for client_id in client_ids}

        if not client_ids:
            return shapley_scores

        self.accuracy_cache = {}
        self.accuracy_cache[tuple()] = self._evaluate_state_dict(base_model_state)

        for _ in range(self.mc_iterations):
            permutation = client_ids.copy()
            random.shuffle(permutation)

            current_subset: List[int] = []
            previous_accuracy = self.accuracy_cache[tuple()]
            for client_id in permutation:
                candidate_subset = tuple(current_subset + [client_id])
                current_accuracy = self._subset_accuracy(candidate_subset, base_model_state, local_updates)
                shapley_scores[client_id] += current_accuracy - previous_accuracy
                current_subset.append(client_id)
                previous_accuracy = current_accuracy

        for client_id in shapley_scores:
            shapley_scores[client_id] /= self.mc_iterations

        return shapley_scores


class BaseFederatedServer:
    def __init__(
        self,
        config: Config,
        scenario: ScenarioSpec,
        clients: List[Client],
        client_loaders: Dict[int, DataLoader],
        val_loader: DataLoader,
        device: torch.device,
    ) -> None:
        self.config = config
        self.scenario = scenario
        self.clients = clients
        self.client_loaders = client_loaders
        self.val_loader = val_loader
        self.device = device
        self.global_model = SimpleCNN(config.NUM_CLASSES).to(device)
        self.model_size_mb = compute_model_size_mb(self.global_model)

        self.accuracy_history: List[float] = []
        self.communication_history_mb: List[float] = []
        self.cumulative_communication_history_mb: List[float] = []
        self.round_spending: List[float] = []
        self.selected_counts: List[int] = []
        self.accepted_counts: List[int] = []
        self.selection_history: List[List[int]] = []
        self.accepted_history: List[List[int]] = []
        self.round_extra_stats: List[Dict[str, Any]] = []
        self.shapley_history: List[Dict[int, float]] = []
        self.reputation_history: Dict[int, List[float]] = {
            client.id: [client.reputation]
            for client in clients
        }

        self.tracked_clean_id = next(
            (client.id for client in clients if not self._is_attacking_client(client)),
            None,
        )
        self.tracked_attack_id = next(
            (client.id for client in clients if self._is_attacking_client(client)),
            None,
        )

    def _is_attacking_client(self, client: Client) -> bool:
        if self.scenario.attack_mode == 'hacker':
            return client.is_hacker
        if self.scenario.attack_mode == 'bid_attack':
            return client.is_bid_attacker
        return False

    def _append_reputation_snapshot(self) -> None:
        for client in self.clients:
            self.reputation_history[client.id].append(client.reputation)

    def _should_log(self, round_idx: int) -> bool:
        return (
            round_idx == 1
            or round_idx % self.config.LOG_EVERY == 0
            or round_idx == self.config.GLOBAL_ROUNDS
        )

    def _apply_global_update(self, accepted_ids: List[int], local_updates: Dict[int, Dict[str, Any]]) -> None:
        if not accepted_ids:
            return
        aggregated_state = fedavg_state_dicts(
            [
                (local_updates[client_id]['weights'], local_updates[client_id]['num_samples'])
                for client_id in accepted_ids
            ]
        )
        self.global_model.load_state_dict(aggregated_state)

    def _compute_round_comm_mb(self, selected_count: int) -> float:
        # Communication = model downlink + local model uplink.
        return self.model_size_mb * selected_count * 2.0

    def _aggregate_numeric_extras(self) -> Dict[str, float]:
        totals: Dict[str, float] = {}
        for stats in self.round_extra_stats:
            for key, value in stats.items():
                if isinstance(value, (int, float, np.integer, np.floating)):
                    totals[key] = totals.get(key, 0.0) + float(value)
        return totals

    def _client_role(self, client: Client) -> str:
        if client.is_hacker:
            return 'Hacker'
        if client.is_bid_attacker:
            return 'Bid Attacker'
        return 'Clean'

    def build_client_summary_df(self) -> pd.DataFrame:
        rows = []
        for client in sorted(self.clients, key=lambda item: item.id):
            rows.append(
                {
                    'Client ID': client.id,
                    'Type': self._client_role(client),
                    'True Cost': round(client.true_cost, 4),
                    'Truthful Bid': round(client.truthful_bid, 4),
                    'Reported Bid': round(client.bid_price, 4),
                    'Total Payment': round(client.total_payment, 4),
                    'Final Reputation': round(client.reputation, 4),
                    'Selected Rounds': client.selected_rounds,
                    'Accepted Rounds': client.accepted_rounds,
                }
            )
        return pd.DataFrame(rows)

    def select_clients(self, round_idx: int):
        raise NotImplementedError

    def handle_round(self, round_idx: int, selected_clients: List[Client], local_updates: Dict[int, Dict[str, Any]], selection_info: Dict[str, Any]):
        raise NotImplementedError

    def run(self) -> Dict[str, Any]:
        start_time = time.time()
        progress_bar = tqdm(
            range(1, self.config.GLOBAL_ROUNDS + 1),
            desc=scenario_label(self.scenario),
            leave=True,
            dynamic_ncols=True,
        )

        for round_idx in progress_bar:
            selected_clients, selection_info = self.select_clients(round_idx)
            selected_ids = [client.id for client in selected_clients]

            local_updates: Dict[int, Dict[str, Any]] = {}
            for client in selected_clients:
                client.selected_rounds += 1
                local_updates[client.id] = client.local_train(self.global_model, self.client_loaders[client.id])

            accepted_ids, round_spending, extra_stats = self.handle_round(
                round_idx,
                selected_clients,
                local_updates,
                selection_info,
            )

            for client in selected_clients:
                if client.id in accepted_ids:
                    client.accepted_rounds += 1

            self._apply_global_update(accepted_ids, local_updates)

            round_comm_mb = self._compute_round_comm_mb(len(selected_clients))
            current_accuracy = evaluate_model(
                self.global_model,
                self.val_loader,
                self.device,
                self.config.NUM_CLASSES,
            )

            self.accuracy_history.append(current_accuracy)
            self.communication_history_mb.append(round_comm_mb)
            self.cumulative_communication_history_mb.append(float(np.sum(self.communication_history_mb)))
            self.round_spending.append(round_spending)
            self.selected_counts.append(len(selected_clients))
            self.accepted_counts.append(len(accepted_ids))
            self.selection_history.append(selected_ids)
            self.accepted_history.append(accepted_ids)
            self.round_extra_stats.append(extra_stats)
            self._append_reputation_snapshot()

            progress_bar.set_postfix(
                acc=f"{current_accuracy:.4f}",
                comm_mb=f"{self.cumulative_communication_history_mb[-1]:.2f}",
                selected=len(selected_ids),
                accepted=len(accepted_ids),
            )

            if self._should_log(round_idx):
                progress_bar.write('-' * 120)
                progress_bar.write(f"{scenario_label(self.scenario)} | Round {round_idx}/{self.config.GLOBAL_ROUNDS}")
                progress_bar.write(f"Selected clients: {selected_ids}")
                progress_bar.write(f"Accepted clients: {accepted_ids}")
                progress_bar.write(f"Validation accuracy: {current_accuracy:.4f}")
                progress_bar.write(f"Communication cost (round / cumulative MB): {round_comm_mb:.4f} / {self.cumulative_communication_history_mb[-1]:.4f}")
                progress_bar.write(f"Payment spent this round: {round_spending:.4f}")
                if 'hackers_caught' in extra_stats:
                    progress_bar.write(f"Hackers caught this round: {int(extra_stats['hackers_caught'])}")

        progress_bar.close()

        final_accuracy, final_confusion_matrix = evaluate_model(
            self.global_model,
            self.val_loader,
            self.device,
            self.config.NUM_CLASSES,
            return_confusion=True,
        )
        total_runtime_seconds = time.time() - start_time
        total_spending = float(np.sum(self.round_spending))
        total_comm_mb = float(np.sum(self.communication_history_mb))
        convergence_round = estimate_convergence_round(self.accuracy_history, self.config.CONVERGENCE_RATIO)

        return {
            'scenario': self.scenario,
            'scenario_label': scenario_label(self.scenario),
            'accuracy_history': self.accuracy_history,
            'communication_history_mb': self.communication_history_mb,
            'cumulative_communication_history_mb': self.cumulative_communication_history_mb,
            'round_spending': self.round_spending,
            'selected_counts': self.selected_counts,
            'accepted_counts': self.accepted_counts,
            'selection_history': self.selection_history,
            'accepted_history': self.accepted_history,
            'extra_stats_total': self._aggregate_numeric_extras(),
            'client_summary_df': self.build_client_summary_df(),
            'reputation_history': self.reputation_history,
            'tracked_clean_id': self.tracked_clean_id,
            'tracked_attack_id': self.tracked_attack_id,
            'final_accuracy': final_accuracy,
            'best_accuracy': max(self.accuracy_history) if self.accuracy_history else 0.0,
            'convergence_round': convergence_round,
            'total_communication_mb': total_comm_mb,
            'total_spending': total_spending,
            'model_size_mb': self.model_size_mb,
            'final_confusion_matrix': final_confusion_matrix,
            'shapley_history': self.shapley_history,
            'last_shapley_scores': self.shapley_history[-1] if self.shapley_history else {},
            'runtime_seconds': total_runtime_seconds,
        }


class VanillaFLServer(BaseFederatedServer):
    def __init__(
        self,
        config: Config,
        scenario: ScenarioSpec,
        clients: List[Client],
        client_loaders: Dict[int, DataLoader],
        val_loader: DataLoader,
        device: torch.device,
    ) -> None:
        super().__init__(config, scenario, clients, client_loaders, val_loader, device)
        self.selection_core = VanillaSelectionCore(config.BUDGET, config.RANDOM_SEED)

    def select_clients(self, round_idx: int):
        selected_clients, spent_budget = self.selection_core.select_clients(self.clients, round_idx)
        return selected_clients, {'spent_budget': spent_budget}

    def handle_round(self, round_idx: int, selected_clients: List[Client], local_updates: Dict[int, Dict[str, Any]], selection_info: Dict[str, Any]):
        accepted_ids = [client.id for client in selected_clients]
        round_spending = 0.0
        selected_attackers = 0
        selected_clean = 0

        for client in selected_clients:
            client.last_payment = client.bid_price
            client.total_payment += client.last_payment
            round_spending += client.last_payment
            if self._is_attacking_client(client):
                selected_attackers += 1
            else:
                selected_clean += 1

        extra_stats = {
            'selected_attackers': selected_attackers,
            'accepted_attackers': selected_attackers,
            'blocked_attackers': 0,
            'selected_clean': selected_clean,
            'accepted_clean': selected_clean,
            'blocked_clean': 0,
            'hackers_caught': 0,
        }
        return accepted_ids, round_spending, extra_stats


class TRASServer(BaseFederatedServer):
    def __init__(
        self,
        config: Config,
        scenario: ScenarioSpec,
        clients: List[Client],
        client_loaders: Dict[int, DataLoader],
        val_loader: DataLoader,
        device: torch.device,
    ) -> None:
        super().__init__(config, scenario, clients, client_loaders, val_loader, device)
        self.economic_core = EconomicCore(config.BUDGET)
        self.security_core = SecurityCore(
            model_factory=lambda: SimpleCNN(config.NUM_CLASSES),
            val_loader=val_loader,
            device=device,
            mc_iterations=config.MC_ITERATIONS,
            num_classes=config.NUM_CLASSES,
        )

    def select_clients(self, round_idx: int):
        selected_clients, payments, first_loser, spent_budget = self.economic_core.select_clients(self.clients)
        return selected_clients, {
            'payments': payments,
            'first_loser': first_loser.id if first_loser is not None else None,
            'spent_budget': spent_budget,
        }

    def handle_round(self, round_idx: int, selected_clients: List[Client], local_updates: Dict[int, Dict[str, Any]], selection_info: Dict[str, Any]):
        payments = selection_info.get('payments', {})
        base_model_state = clone_state_dict(self.global_model.state_dict())
        shapley_scores = self.security_core.mc_sva(base_model_state, local_updates)
        self.shapley_history.append(shapley_scores.copy())

        accepted_ids = [client_id for client_id, score in shapley_scores.items() if score > 0.0]
        selected_id_set = {client.id for client in selected_clients}
        round_spending = 0.0
        selected_attackers = 0
        selected_clean = 0
        accepted_attackers = 0
        accepted_clean = 0
        blocked_attackers = 0
        blocked_clean = 0

        for client in self.clients:
            if client.id not in selected_id_set:
                client.last_payment = 0.0
                continue

            if self._is_attacking_client(client):
                selected_attackers += 1
            else:
                selected_clean += 1

            shapley_value = shapley_scores.get(client.id, 0.0)
            if shapley_value > 0.0:
                client.last_payment = float(payments.get(client.id, 0.0))
                client.total_payment += client.last_payment
                client.reputation += self.config.REPUTATION_REWARD
                round_spending += client.last_payment
                if self._is_attacking_client(client):
                    accepted_attackers += 1
                else:
                    accepted_clean += 1
            else:
                client.last_payment = 0.0
                client.reputation = max(0.0, client.reputation - self.config.REPUTATION_PENALTY)
                if self._is_attacking_client(client):
                    blocked_attackers += 1
                else:
                    blocked_clean += 1

        extra_stats = {
            'selected_attackers': selected_attackers,
            'accepted_attackers': accepted_attackers,
            'blocked_attackers': blocked_attackers,
            'selected_clean': selected_clean,
            'accepted_clean': accepted_clean,
            'blocked_clean': blocked_clean,
            'hackers_caught': blocked_attackers if self.scenario.attack_mode == 'hacker' else 0,
        }
        return accepted_ids, round_spending, extra_stats


def build_client_blueprints(config: Config) -> List[ClientBlueprint]:
    rng = np.random.default_rng(config.RANDOM_SEED)
    client_ids = np.arange(config.NUM_CLIENTS)
    num_hackers = max(1, int(config.NUM_CLIENTS * config.HACKER_RATIO))
    num_bid_attackers = max(1, int(config.NUM_CLIENTS * config.BID_ATTACK_RATIO))

    hacker_ids = set(rng.choice(client_ids, size=num_hackers, replace=False).tolist())
    bid_attacker_ids = set(rng.choice(client_ids, size=num_bid_attackers, replace=False).tolist())

    blueprints: List[ClientBlueprint] = []
    for client_id in client_ids:
        true_cost = float(rng.uniform(4.0, 8.0))
        truthful_bid = true_cost
        manipulated_bid = float(true_cost * config.BID_ATTACK_MULTIPLIER)
        blueprints.append(
            ClientBlueprint(
                client_id=int(client_id),
                true_cost=true_cost,
                truthful_bid=truthful_bid,
                manipulated_bid=manipulated_bid,
                is_bid_attacker=int(client_id) in bid_attacker_ids,
                is_hacker=int(client_id) in hacker_ids,
            )
        )
    return blueprints


def instantiate_clients_for_scenario(
    blueprints: List[ClientBlueprint],
    scenario: ScenarioSpec,
    config: Config,
    device: torch.device,
) -> List[Client]:
    clients: List[Client] = []

    for blueprint in blueprints:
        is_hacker = scenario.attack_mode == 'hacker' and blueprint.is_hacker
        is_bid_attacker = scenario.attack_mode == 'bid_attack' and blueprint.is_bid_attacker

        # In the dishonest bidding case, the baseline uses manipulated bids while T-RAS uses truthful bids.
        if scenario.attack_mode == 'bid_attack' and scenario.mechanism == 'Vanilla FL':
            reported_bid = blueprint.manipulated_bid if blueprint.is_bid_attacker else blueprint.truthful_bid
        else:
            reported_bid = blueprint.truthful_bid

        clients.append(
            Client(
                client_id=blueprint.client_id,
                true_cost=blueprint.true_cost,
                truthful_bid=blueprint.truthful_bid,
                bid_price=reported_bid,
                config=config,
                device=device,
                is_hacker=is_hacker,
                is_bid_attacker=is_bid_attacker,
            )
        )

    return clients

In [ ]:
blueprints = build_client_blueprints(cfg)
blueprint_df = pd.DataFrame(
    [
        {
            'Client ID': blueprint.client_id,
            'True Cost': round(blueprint.true_cost, 4),
            'Truthful Bid': round(blueprint.truthful_bid, 4),
            'Manipulated Bid': round(blueprint.manipulated_bid, 4),
            'Bid Attacker': blueprint.is_bid_attacker,
            'Hacker': blueprint.is_hacker,
        }
        for blueprint in blueprints
    ]
)
display(blueprint_df)

scenario_specs = [
    ScenarioSpec(
        scenario_id='S1',
        title='Clean Data + Vanilla FL',
        case_name='Clean',
        mechanism='Vanilla FL',
        attack_mode='clean',
        description='Clean data, no attack, baseline budgeted FedAvg.',
    ),
    ScenarioSpec(
        scenario_id='S2',
        title='Clean Data + T-RAS',
        case_name='Clean',
        mechanism='T-RAS',
        attack_mode='clean',
        description='Clean data, no attack, using EconomicCore + SecurityCore.',
    ),
    ScenarioSpec(
        scenario_id='S3',
        title='Dishonest Bidding + Vanilla FL',
        case_name='Dishonest Bid Attack',
        mechanism='Vanilla FL',
        attack_mode='bid_attack',
        description='Malicious bidders over-report cost and reduce budget efficiency under the baseline.',
    ),
    ScenarioSpec(
        scenario_id='S4',
        title='Dishonest Bidding + T-RAS',
        case_name='Dishonest Bid Attack',
        mechanism='T-RAS',
        attack_mode='bid_attack',
        description='T-RAS simulates truthful bidding under the Myerson-style mechanism.',
    ),
    ScenarioSpec(
        scenario_id='S5',
        title='Hacker Poisoning + Vanilla FL',
        case_name='Hacker Poisoning',
        mechanism='Vanilla FL',
        attack_mode='hacker',
        description='Hackers perform label flipping while the baseline has no dedicated defense.',
    ),
    ScenarioSpec(
        scenario_id='S6',
        title='Hacker Poisoning + T-RAS',
        case_name='Hacker Poisoning',
        mechanism='T-RAS',
        attack_mode='hacker',
        description='T-RAS uses MC-SVA to filter harmful model updates.',
    ),
]

scenario_results: Dict[str, Dict[str, Any]] = OrderedDict()
benchmark_rows = []

for scenario in scenario_specs:
    print('\n' + '#' * 120)
    print(f"STARTING {scenario_label(scenario)}")
    print(scenario.description)
    print('#' * 120)

    clients = instantiate_clients_for_scenario(blueprints, scenario, cfg, device)
    if scenario.mechanism == 'Vanilla FL':
        server = VanillaFLServer(cfg, scenario, clients, client_loaders, val_loader, device)
    else:
        server = TRASServer(cfg, scenario, clients, client_loaders, val_loader, device)

    result = server.run()
    scenario_results[scenario.scenario_id] = result

    extra_stats_total = result['extra_stats_total']
    benchmark_rows.append(
        {
            'Scenario ID': scenario.scenario_id,
            'Scenario': scenario.title,
            'Case': scenario.case_name,
            'Mechanism': scenario.mechanism,
            'Final Accuracy': round(result['final_accuracy'], 6),
            'Best Accuracy': round(result['best_accuracy'], 6),
            'Convergence Round': int(result['convergence_round']),
            'Total Communication (MB)': round(result['total_communication_mb'], 4),
            'Total Spending': round(result['total_spending'], 4),
            'Avg Selected Clients / Round': round(float(np.mean(result['selected_counts'])), 4),
            'Avg Accepted Clients / Round': round(float(np.mean(result['accepted_counts'])), 4),
            'Blocked Attackers': int(extra_stats_total.get('blocked_attackers', 0)),
            'Accepted Attackers': int(extra_stats_total.get('accepted_attackers', 0)),
            'Runtime (s)': round(result['runtime_seconds'], 2),
        }
    )

benchmark_df = pd.DataFrame(benchmark_rows).sort_values('Scenario ID').reset_index(drop=True)
print('\nBENCHMARK SUMMARY TABLE')
display(benchmark_df)

    Client ID  True Cost  Truthful Bid  Manipulated Bid  Bid Attacker  Hacker
0           0     5.8015        5.8015          13.9237         False   False
1           1     5.4832        5.4832          13.1597          True    True
2           2     7.7071        7.7071          18.4969         False   False
3           3     6.5755        6.5755          15.7811          True   False
4           4     7.2910        7.2910          17.4985         False   False
5           5     5.7737        5.7737          13.8568         False   False
6           6     4.9090        4.9090          11.7815         False   False
7           7     6.2183        6.2183          14.9240         False   False
8           8     4.2553        4.2553          10.2126         False    True
9           9     7.3105        7.3105          17.5453          True   False
10         10     6.5267        6.5267          15.6640          True   False
11         11     7.0324        7.0324          16.8776         False   False
12         12     5.4181        5.4181          13.0034         False    True
13         13     7.8828        7.8828          18.9187         False    True
14         14     7.5725        7.5725          18.1740          True   False
15         15     7.1135        7.1135          17.0725         False   False
16         16     4.7786        4.7786          11.4685         False   False
17         17     5.8669        5.8669          14.0805         False   False
18         18     4.1752        4.1752          10.0205          True   False
19         19     4.6172        4.6172          11.0812         False   False

########################################################################################################################
STARTING S1 | Clean Data + Vanilla FL
Clean data, no attack, baseline budgeted FedAvg.
########################################################################################################################

S1 | Clean Data + Vanilla FL:   0%|          | 0/100 [00:00<?, ?it/s]

------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 1/100
Selected clients: [8, 13, 5, 2, 6, 3, 17, 0, 16, 18, 7, 19, 12, 15, 10, 11]
Accepted clients: [8, 13, 5, 2, 6, 3, 17, 0, 16, 18, 7, 19, 12, 15, 10, 11]
Validation accuracy: 0.7268
Communication cost (round / cumulative MB): 51.8794 / 51.8794
Payment spent this round: 94.6515
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 2/100
Selected clients: [8, 14, 15, 10, 2, 12, 7, 9, 11, 1, 19, 0, 4, 18, 6, 5]
Accepted clients: [8, 14, 15, 10, 2, 12, 7, 9, 11, 1, 19, 0, 4, 18, 6, 5]
Validation accuracy: 0.8562
Communication cost (round / cumulative MB): 51.8794 / 103.7588
Payment spent this round: 97.2051
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 3/100
Selected clients: [16, 3, 10, 18, 17, 9, 6, 14, 11, 12, 7, 1, 0, 5, 4, 2]
Accepted clients: [16, 3, 10, 18, 17, 9, 6, 14, 11, 12, 7, 1, 0, 5, 4, 2]
Validation accuracy: 0.8912
Communication cost (round / cumulative MB): 51.8794 / 155.6382
Payment spent this round: 98.4400
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 4/100
Selected clients: [13, 15, 3, 19, 14, 16, 6, 10, 5, 17, 11, 0, 18, 8, 9, 4]
Accepted clients: [13, 15, 3, 19, 14, 16, 6, 10, 5, 17, 11, 0, 18, 8, 9, 4]
Validation accuracy: 0.8940
Communication cost (round / cumulative MB): 51.8794 / 207.5176
Payment spent this round: 97.4821
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 5/100
Selected clients: [1, 5, 16, 3, 18, 17, 7, 15, 19, 0, 9, 12, 6, 8, 4, 10, 14]
Accepted clients: [1, 5, 16, 3, 18, 17, 7, 15, 19, 0, 9, 12, 6, 8, 4, 10, 14]
Validation accuracy: 0.9105
Communication cost (round / cumulative MB): 55.1219 / 262.6394
Payment spent this round: 99.6866
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 6/100
Selected clients: [18, 0, 8, 13, 5, 19, 16, 3, 7, 1, 14, 2, 15, 12, 11, 6]
Accepted clients: [18, 0, 8, 13, 5, 19, 16, 3, 7, 1, 14, 2, 15, 12, 11, 6]
Validation accuracy: 0.9140
Communication cost (round / cumulative MB): 51.8794 / 314.5188
Payment spent this round: 95.3137
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 7/100
Selected clients: [14, 6, 7, 1, 9, 5, 16, 19, 4, 18, 15, 0, 17, 8, 12, 10, 3]
Accepted clients: [14, 6, 7, 1, 9, 5, 16, 19, 4, 18, 15, 0, 17, 8, 12, 10, 3]
Validation accuracy: 0.9183
Communication cost (round / cumulative MB): 55.1219 / 369.6407
Payment spent this round: 99.6866
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 8/100
Selected clients: [9, 4, 6, 10, 0, 2, 16, 14, 17, 3, 13, 18, 1, 5, 12, 19]
Accepted clients: [9, 4, 6, 10, 0, 2, 16, 14, 17, 3, 13, 18, 1, 5, 12, 19]
Validation accuracy: 0.9135
Communication cost (round / cumulative MB): 51.8794 / 421.5201
Payment spent this round: 97.6893
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 9/100
Selected clients: [0, 10, 1, 14, 2, 9, 11, 18, 15, 12, 6, 4, 8, 3, 13, 19]
Accepted clients: [0, 10, 1, 14, 2, 9, 11, 18, 15, 12, 6, 4, 8, 3, 13, 19]
Validation accuracy: 0.9193
Communication cost (round / cumulative MB): 51.8794 / 473.3995
Payment spent this round: 99.6713
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 10/100
Selected clients: [9, 4, 18, 3, 10, 13, 19, 7, 5, 17, 14, 12, 2, 0, 6, 16]
Accepted clients: [9, 4, 18, 3, 10, 13, 19, 7, 5, 17, 14, 12, 2, 0, 6, 16]
Validation accuracy: 0.9180
Communication cost (round / cumulative MB): 51.8794 / 525.2789
Payment spent this round: 98.4244
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 11/100
Selected clients: [4, 12, 3, 18, 1, 13, 10, 2, 9, 0, 7, 5, 8, 11, 17, 16]
Accepted clients: [4, 12, 3, 18, 1, 13, 10, 2, 9, 0, 7, 5, 8, 11, 17, 16]
Validation accuracy: 0.9210
Communication cost (round / cumulative MB): 51.8794 / 577.1583
Payment spent this round: 98.0967
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 12/100
Selected clients: [19, 8, 2, 10, 0, 1, 16, 11, 12, 5, 13, 3, 6, 7, 18, 15]
Accepted clients: [19, 8, 2, 10, 0, 1, 16, 11, 12, 5, 13, 3, 6, 7, 18, 15]
Validation accuracy: 0.9245
Communication cost (round / cumulative MB): 51.8794 / 629.0377
Payment spent this round: 94.2678
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 13/100
Selected clients: [0, 14, 10, 13, 16, 12, 3, 18, 8, 7, 5, 1, 17, 15, 11, 19]
Accepted clients: [0, 14, 10, 13, 16, 12, 3, 18, 8, 7, 5, 1, 17, 15, 11, 19]
Validation accuracy: 0.9237
Communication cost (round / cumulative MB): 51.8794 / 680.9171
Payment spent this round: 95.0912
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 14/100
Selected clients: [10, 4, 18, 7, 14, 13, 2, 19, 5, 1, 3, 11, 6, 8, 12, 9]
Accepted clients: [10, 4, 18, 7, 14, 13, 2, 19, 5, 1, 3, 11, 6, 8, 12, 9]
Validation accuracy: 0.9175
Communication cost (round / cumulative MB): 51.8794 / 732.7964
Payment spent this round: 98.7483
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 15/100
Selected clients: [13, 19, 8, 14, 9, 18, 3, 5, 2, 17, 12, 15, 6, 4, 16, 10]
Accepted clients: [13, 19, 8, 14, 9, 18, 3, 5, 2, 17, 12, 15, 6, 4, 16, 10]
Validation accuracy: 0.9125
Communication cost (round / cumulative MB): 51.8794 / 784.6758
Payment spent this round: 97.7734
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 16/100
Selected clients: [8, 14, 15, 11, 0, 9, 2, 12, 13, 10, 4, 5, 16, 7, 3]
Accepted clients: [8, 14, 15, 11, 0, 9, 2, 12, 13, 10, 4, 5, 16, 7, 3]
Validation accuracy: 0.9250
Communication cost (round / cumulative MB): 48.6369 / 833.3128
Payment spent this round: 97.2574
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 17/100
Selected clients: [5, 1, 8, 18, 17, 6, 3, 19, 12, 9, 10, 16, 11, 15, 13, 4]
Accepted clients: [5, 1, 8, 18, 17, 6, 3, 19, 12, 9, 10, 16, 11, 15, 13, 4]
Validation accuracy: 0.9245
Communication cost (round / cumulative MB): 51.8794 / 885.1922
Payment spent this round: 95.0094
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 18/100
Selected clients: [14, 6, 17, 11, 18, 10, 3, 16, 2, 1, 0, 5, 13, 15, 12, 7]
Accepted clients: [14, 6, 17, 11, 18, 10, 3, 16, 2, 1, 0, 5, 13, 15, 12, 7]
Validation accuracy: 0.9233
Communication cost (round / cumulative MB): 51.8794 / 937.0716
Payment spent this round: 98.8348
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 19/100
Selected clients: [14, 1, 16, 2, 9, 3, 19, 8, 13, 7, 0, 11, 12, 18, 4, 10]
Accepted clients: [14, 1, 16, 2, 9, 3, 19, 8, 13, 7, 0, 11, 12, 18, 4, 10]
Validation accuracy: 0.9175
Communication cost (round / cumulative MB): 51.8794 / 988.9510
Payment spent this round: 98.6458
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 20/100
Selected clients: [6, 15, 3, 16, 1, 12, 13, 0, 9, 11, 8, 17, 19, 10, 4, 14]
Accepted clients: [6, 15, 3, 16, 1, 12, 13, 0, 9, 11, 8, 17, 19, 10, 4, 14]
Validation accuracy: 0.9255
Communication cost (round / cumulative MB): 51.8794 / 1040.8304
Payment spent this round: 98.4345
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 21/100
Selected clients: [17, 7, 16, 12, 2, 5, 0, 4, 3, 18, 13, 11, 6, 1, 10, 15]
Accepted clients: [17, 7, 16, 12, 2, 5, 0, 4, 3, 18, 13, 11, 6, 1, 10, 15]
Validation accuracy: 0.9257
Communication cost (round / cumulative MB): 51.8794 / 1092.7097
Payment spent this round: 98.5533
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 22/100
Selected clients: [9, 7, 5, 14, 16, 8, 13, 19, 1, 2, 18, 10, 17, 11, 4, 6]
Accepted clients: [9, 7, 5, 14, 16, 8, 13, 19, 1, 2, 18, 10, 17, 11, 4, 6]
Validation accuracy: 0.9165
Communication cost (round / cumulative MB): 51.8794 / 1144.5891
Payment spent this round: 97.4001
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 23/100
Selected clients: [17, 1, 10, 2, 11, 4, 0, 3, 6, 5, 12, 19, 8, 14, 15, 7]
Accepted clients: [17, 1, 10, 2, 11, 4, 0, 3, 6, 5, 12, 19, 8, 14, 15, 7]
Validation accuracy: 0.9270
Communication cost (round / cumulative MB): 51.8794 / 1196.4685
Payment spent this round: 98.1617
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 24/100
Selected clients: [5, 6, 3, 11, 0, 10, 17, 18, 19, 16, 1, 8, 12, 15, 4, 14, 7]
Accepted clients: [5, 6, 3, 11, 0, 10, 17, 18, 19, 16, 1, 8, 12, 15, 4, 14, 7]
Validation accuracy: 0.9275
Communication cost (round / cumulative MB): 55.1219 / 1251.5904
Payment spent this round: 99.4084
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 25/100
Selected clients: [10, 12, 8, 11, 19, 1, 5, 0, 18, 16, 15, 7, 6, 9, 4, 17, 3]
Accepted clients: [10, 12, 8, 11, 19, 1, 5, 0, 18, 16, 15, 7, 6, 9, 4, 17, 3]
Validation accuracy: 0.9270
Communication cost (round / cumulative MB): 55.1219 / 1306.7122
Payment spent this round: 99.1464
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 26/100
Selected clients: [17, 6, 2, 9, 0, 15, 1, 12, 8, 19, 5, 10, 11, 4, 18, 13]
Accepted clients: [17, 6, 2, 9, 0, 15, 1, 12, 8, 19, 5, 10, 11, 4, 18, 13]
Validation accuracy: 0.9245
Communication cost (round / cumulative MB): 51.8794 / 1358.5916
Payment spent this round: 97.1639
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 27/100
Selected clients: [14, 19, 0, 18, 16, 4, 15, 9, 10, 7, 6, 8, 12, 13, 17, 11]
Accepted clients: [14, 19, 0, 18, 16, 4, 15, 9, 10, 7, 6, 8, 12, 13, 17, 11]
Validation accuracy: 0.9230
Communication cost (round / cumulative MB): 51.8794 / 1410.4710
Payment spent this round: 96.7694
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 28/100
Selected clients: [15, 0, 12, 16, 13, 8, 7, 6, 19, 18, 11, 10, 2, 1, 5, 4]
Accepted clients: [15, 0, 12, 16, 13, 8, 7, 6, 19, 18, 11, 10, 2, 1, 5, 4]
Validation accuracy: 0.9235
Communication cost (round / cumulative MB): 51.8794 / 1462.3504
Payment spent this round: 94.9834
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 29/100
Selected clients: [9, 5, 2, 7, 6, 19, 11, 17, 18, 14, 1, 15, 3, 12, 13, 8]
Accepted clients: [9, 5, 2, 7, 6, 19, 11, 17, 18, 14, 1, 15, 3, 12, 13, 8]
Validation accuracy: 0.9273
Communication cost (round / cumulative MB): 51.8794 / 1514.2298
Payment spent this round: 97.9110
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 30/100
Selected clients: [12, 4, 8, 7, 0, 13, 1, 6, 3, 18, 19, 15, 10, 14, 16, 9]
Accepted clients: [12, 4, 8, 7, 0, 13, 1, 6, 3, 18, 19, 15, 10, 14, 16, 9]
Validation accuracy: 0.9243
Communication cost (round / cumulative MB): 51.8794 / 1566.1092
Payment spent this round: 95.9288
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 31/100
Selected clients: [12, 13, 11, 2, 17, 0, 10, 18, 19, 6, 14, 1, 9, 4, 7, 5]
Accepted clients: [12, 13, 11, 2, 17, 0, 10, 18, 19, 6, 14, 1, 9, 4, 7, 5]
Validation accuracy: 0.9217
Communication cost (round / cumulative MB): 51.8794 / 1617.9886
Payment spent this round: 99.5860
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 32/100
Selected clients: [0, 18, 6, 9, 11, 14, 13, 8, 7, 1, 5, 15, 2, 4, 12, 17]
Accepted clients: [0, 18, 6, 9, 11, 14, 13, 8, 7, 1, 5, 15, 2, 4, 12, 17]
Validation accuracy: 0.9267
Communication cost (round / cumulative MB): 51.8794 / 1669.8680
Payment spent this round: 99.8110
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 33/100
Selected clients: [4, 3, 9, 6, 0, 2, 17, 15, 5, 7, 16, 10, 8, 12, 11, 1]
Accepted clients: [4, 3, 9, 6, 0, 2, 17, 15, 5, 7, 16, 10, 8, 12, 11, 1]
Validation accuracy: 0.9283
Communication cost (round / cumulative MB): 51.8794 / 1721.7474
Payment spent this round: 98.0611
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 34/100
Selected clients: [10, 13, 8, 1, 5, 2, 18, 17, 15, 7, 19, 4, 3, 16, 0, 9]
Accepted clients: [10, 13, 8, 1, 5, 2, 18, 17, 15, 7, 19, 4, 3, 16, 0, 9]
Validation accuracy: 0.9285
Communication cost (round / cumulative MB): 51.8794 / 1773.6268
Payment spent this round: 97.3769
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 35/100
Selected clients: [11, 18, 14, 0, 15, 5, 12, 2, 3, 9, 19, 16, 4, 1, 13, 6]
Accepted clients: [11, 18, 14, 0, 15, 5, 12, 2, 3, 9, 19, 16, 4, 1, 13, 6]
Validation accuracy: 0.9207
Communication cost (round / cumulative MB): 51.8794 / 1825.5062
Payment spent this round: 99.4416
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 36/100
Selected clients: [17, 5, 11, 1, 15, 4, 16, 7, 18, 19, 12, 2, 10, 0, 14, 13]
Accepted clients: [17, 5, 11, 1, 15, 4, 16, 7, 18, 19, 12, 2, 10, 0, 14, 13]
Validation accuracy: 0.9220
Communication cost (round / cumulative MB): 51.8794 / 1877.3856
Payment spent this round: 99.2586
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 37/100
Selected clients: [19, 6, 8, 10, 18, 12, 9, 0, 16, 1, 2, 15, 13, 17, 3, 7]
Accepted clients: [19, 6, 8, 10, 18, 12, 9, 0, 16, 1, 2, 15, 13, 17, 3, 7]
Validation accuracy: 0.9265
Communication cost (round / cumulative MB): 51.8794 / 1929.2650
Payment spent this round: 94.6392
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 38/100
Selected clients: [9, 2, 15, 1, 7, 10, 4, 3, 18, 16, 0, 14, 6, 19, 5, 11]
Accepted clients: [9, 2, 15, 1, 7, 10, 4, 3, 18, 16, 0, 14, 6, 19, 5, 11]
Validation accuracy: 0.9237
Communication cost (round / cumulative MB): 51.8794 / 1981.1444
Payment spent this round: 98.8857
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 39/100
Selected clients: [4, 8, 3, 1, 6, 17, 11, 5, 18, 9, 7, 19, 2, 0, 13, 15]
Accepted clients: [4, 8, 3, 1, 6, 17, 11, 5, 18, 9, 7, 19, 2, 0, 13, 15]
Validation accuracy: 0.9275
Communication cost (round / cumulative MB): 51.8794 / 2033.0238
Payment spent this round: 98.0130
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 40/100
Selected clients: [8, 18, 3, 14, 1, 17, 11, 7, 6, 0, 13, 19, 10, 2, 12, 5]
Accepted clients: [8, 18, 3, 14, 1, 17, 11, 7, 6, 0, 13, 19, 10, 2, 12, 5]
Validation accuracy: 0.9203
Communication cost (round / cumulative MB): 51.8794 / 2084.9032
Payment spent this round: 95.8151
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 41/100
Selected clients: [5, 9, 8, 7, 19, 13, 6, 1, 16, 17, 11, 3, 10, 18, 0, 12, 4]
Accepted clients: [5, 9, 8, 7, 19, 13, 6, 1, 16, 17, 11, 3, 10, 18, 0, 12, 4]
Validation accuracy: 0.9253
Communication cost (round / cumulative MB): 55.1219 / 2140.0250
Payment spent this round: 99.9157
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 42/100
Selected clients: [18, 16, 6, 17, 19, 14, 11, 4, 2, 5, 8, 12, 7, 3, 13, 10]
Accepted clients: [18, 16, 6, 17, 19, 14, 11, 4, 2, 5, 8, 12, 7, 3, 13, 10]
Validation accuracy: 0.9135
Communication cost (round / cumulative MB): 51.8794 / 2191.9044
Payment spent this round: 96.6000
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S1 | Clean Data + Vanilla FL | Round 43/100
Selected clients: [0, 1, 2, 14, 4, 11, 8, 17, 16, 18, 9, 5, 13, 12, 15, 7]

S2 | Clean Data + T-RAS:   0%|          | 0/100 [00:00<?, ?it/s]

------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 1/100
Selected clients: [18, 8, 19, 16, 6, 12, 1, 5, 0, 17, 7, 10, 3, 11, 15, 4, 9]
Accepted clients: [18, 19, 16, 6, 12, 5, 0, 17, 7, 10, 3, 11, 15, 4, 9]
Validation accuracy: 0.7095
Communication cost (round / cumulative MB): 55.1219 / 55.1219
Payment spent this round: 113.5873
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 2/100
Selected clients: [18, 19, 16, 6, 12, 5, 0, 17, 7, 10, 3, 11, 15, 4, 9, 8, 1]
Accepted clients: [19, 6, 12, 5, 0, 17, 7, 10, 3, 15, 9, 8, 1]
Validation accuracy: 0.8702
Communication cost (round / cumulative MB): 55.1219 / 110.2437
Payment spent this round: 100.7140
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 3/100
Selected clients: [19, 6, 12, 5, 0, 17, 7, 10, 3, 15, 18, 8, 9, 16, 14, 2]
Accepted clients: [12, 5, 0, 7, 3, 15, 8, 9, 16]
Validation accuracy: 0.8905
Communication cost (round / cumulative MB): 51.8794 / 162.1231
Payment spent this round: 76.7647
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 4/100
Selected clients: [12, 5, 0, 7, 3, 8, 15, 9, 19, 16, 6, 17, 1, 13, 10, 11, 18]
Accepted clients: [12, 5, 0, 7, 3, 8, 15, 9, 19, 6, 17]
Validation accuracy: 0.9052
Communication cost (round / cumulative MB): 55.1219 / 217.2450
Payment spent this round: 128.1141
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 5/100
Selected clients: [12, 5, 0, 7, 3, 8, 15, 19, 9, 6, 17, 4, 16, 14, 2, 13]
Accepted clients: [12, 5, 0, 7, 15, 19, 9, 6, 17, 4, 16]
Validation accuracy: 0.9153
Communication cost (round / cumulative MB): 51.8794 / 269.1244
Payment spent this round: 199.0631
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 6/100
Selected clients: [12, 5, 0, 7, 19, 15, 9, 6, 17, 3, 8, 4, 16, 10, 1, 11, 18]
Accepted clients: [5, 0, 7, 19, 15, 6, 3, 8, 4, 16, 11]
Validation accuracy: 0.9147
Communication cost (round / cumulative MB): 55.1219 / 324.2462
Payment spent this round: 420.2729
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 7/100
Selected clients: [5, 0, 7, 19, 15, 6, 12, 3, 9, 8, 16, 4, 17, 11, 14, 2]
Accepted clients: [5, 0, 7, 19, 15, 3, 8, 4, 17]
Validation accuracy: 0.9190
Communication cost (round / cumulative MB): 51.8794 / 376.1256
Payment spent this round: 421.7294
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 8/100
Selected clients: [5, 0, 7, 19, 15, 3, 8, 6, 4, 12, 17, 9, 16, 13, 1, 2]
Accepted clients: [5, 0, 7, 15, 3, 8, 12, 17, 16, 1, 2]
Validation accuracy: 0.9197
Communication cost (round / cumulative MB): 51.8794 / 428.0050
Payment spent this round: 33612286621.9145
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 9/100
Selected clients: [5, 0, 7, 15, 3, 8, 19, 12, 17, 4, 16, 6, 9, 1, 2, 10, 18]
Accepted clients: [0, 15, 3, 17, 16, 6, 1, 2, 10]
Validation accuracy: 0.9225
Communication cost (round / cumulative MB): 55.1219 / 483.1269
Payment spent this round: 22855140621.1099
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 10/100
Selected clients: [0, 15, 5, 7, 3, 17, 8, 19, 16, 6, 12, 1, 4, 2, 10, 9, 18]
Accepted clients: [0, 15, 5, 7, 8, 19, 16, 6, 12, 1]
Validation accuracy: 0.9243
Communication cost (round / cumulative MB): 55.1219 / 538.2487
Payment spent this round: 30942344225.5026
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 11/100
Selected clients: [0, 15, 5, 7, 3, 8, 19, 16, 6, 12, 17, 1, 2, 4, 9, 10, 18]
Accepted clients: [0, 15, 7, 3, 19, 12, 17, 2, 9]
Validation accuracy: 0.9255
Communication cost (round / cumulative MB): 55.1219 / 593.3706
Payment spent this round: 28129403841.3660
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 12/100
Selected clients: [0, 15, 7, 5, 3, 19, 12, 17, 8, 16, 6, 9, 2, 1, 4, 10, 18]
Accepted clients: [0, 7, 3, 19, 12, 17, 8, 6, 2, 1, 10]
Validation accuracy: 0.9250
Communication cost (round / cumulative MB): 55.1219 / 648.4924
Payment spent this round: 24261610813.1782
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 13/100
Selected clients: [0, 7, 15, 3, 19, 12, 5, 17, 8, 6, 2, 1, 10, 4, 9, 11]
Accepted clients: [0, 7, 3, 12, 5, 8, 6, 2, 9, 11]
Validation accuracy: 0.9240
Communication cost (round / cumulative MB): 51.8794 / 700.3718
Payment spent this round: 27983911946.4076
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 14/100
Selected clients: [0, 7, 3, 15, 12, 5, 8, 19, 6, 17, 2, 11, 9, 1, 4, 10]
Accepted clients: [0, 7, 3, 15, 12, 5, 6, 17, 9, 4]
Validation accuracy: 0.9283
Communication cost (round / cumulative MB): 51.8794 / 752.2512
Payment spent this round: 35472564439.1083
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 15/100
Selected clients: [0, 7, 3, 15, 12, 5, 6, 17, 9, 4, 1, 2, 8, 10, 11, 16]
Accepted clients: [7, 15, 6, 4, 1, 2, 8, 10]
Validation accuracy: 0.9260
Communication cost (round / cumulative MB): 51.8794 / 804.1306
Payment spent this round: 14977304985.4013
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 16/100
Selected clients: [0, 7, 15, 3, 6, 12, 5, 4, 8, 1, 10, 2, 9, 11, 13, 18]
Accepted clients: [0, 7, 15, 3, 6, 12, 5, 4, 8, 11]
Validation accuracy: 0.9307
Communication cost (round / cumulative MB): 51.8794 / 856.0100
Payment spent this round: 31425810613.9485
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 17/100
Selected clients: [0, 7, 15, 3, 6, 12, 5, 8, 4, 11, 1, 2, 9, 10, 13, 18]
Accepted clients: [15, 3, 6, 5, 8, 4, 11, 1]
Validation accuracy: 0.9243
Communication cost (round / cumulative MB): 51.8794 / 907.8894
Payment spent this round: 17038090091.8998
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 18/100
Selected clients: [0, 7, 15, 3, 6, 5, 8, 4, 12, 11, 1, 2, 9, 10, 13, 18]
Accepted clients: [0, 7, 15, 3, 5, 8, 4, 9]
Validation accuracy: 0.9290
Communication cost (round / cumulative MB): 51.8794 / 959.7688
Payment spent this round: 29154065268.3618
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 19/100
Selected clients: [0, 7, 15, 3, 5, 8, 4, 6, 9, 1, 2, 10, 11, 12, 13, 18]
Accepted clients: [0, 7, 15, 3, 8, 6, 9, 1, 10, 12, 13]
Validation accuracy: 0.9275
Communication cost (round / cumulative MB): 51.8794 / 1011.6482
Payment spent this round: 28396816819.8330
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 20/100
Selected clients: [0, 7, 15, 3, 8, 6, 5, 9, 12, 1, 10, 4, 13, 2, 11, 18]
Accepted clients: [7, 15, 8, 5, 12, 10, 13, 11]
Validation accuracy: 0.9275
Communication cost (round / cumulative MB): 51.8794 / 1063.5276
Payment spent this round: 18931211213.2220
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 21/100
Selected clients: [7, 15, 0, 3, 8, 5, 12, 10, 13, 11, 1, 2, 4, 6, 9, 18]
Accepted clients: [15, 0, 3, 8, 12, 11, 1, 2, 6, 18]
Validation accuracy: 0.9275
Communication cost (round / cumulative MB): 51.8794 / 1115.4070
Payment spent this round: 20445708110.2797
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 22/100
Selected clients: [15, 0, 7, 3, 8, 12, 11, 18, 6, 1, 5, 2, 4, 9, 10, 13]
Accepted clients: [15, 0, 3, 8, 12, 6, 5]
Validation accuracy: 0.9300
Communication cost (round / cumulative MB): 51.8794 / 1167.2864
Payment spent this round: 22717453455.8664
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 23/100
Selected clients: [15, 0, 7, 8, 3, 12, 6, 5, 1, 2, 4, 9, 10, 11, 13, 18]
Accepted clients: [15, 7, 8, 3, 12, 6, 9, 10, 11, 13]
Validation accuracy: 0.9280
Communication cost (round / cumulative MB): 51.8794 / 1219.1658
Payment spent this round: 22717453455.8664
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 24/100
Selected clients: [15, 0, 8, 7, 3, 12, 6, 10, 11, 9, 13, 1, 2, 4, 5, 18]
Accepted clients: [15, 8, 7, 3, 6, 9, 1, 18]
Validation accuracy: 0.9247
Communication cost (round / cumulative MB): 51.8794 / 1271.0452
Payment spent this round: 23474701904.3952
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 25/100
Selected clients: [15, 8, 7, 3, 0, 6, 9, 18, 12, 1, 2, 4, 5, 10, 11, 13]
Accepted clients: [15, 8, 7, 0, 9, 12, 4, 5, 11, 13]
Validation accuracy: 0.9260
Communication cost (round / cumulative MB): 51.8794 / 1322.9246
Payment spent this round: 22717453455.8664
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 26/100
Selected clients: [15, 8, 7, 0, 3, 9, 12, 5, 11, 4, 13, 1, 2, 6, 10, 18]
Accepted clients: [15, 8, 7, 0, 3, 9, 12, 4, 6]
Validation accuracy: 0.9283
Communication cost (round / cumulative MB): 51.8794 / 1374.8040
Payment spent this round: 29154065268.3618
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 27/100
Selected clients: [15, 8, 7, 0, 3, 12, 9, 4, 6, 1, 2, 5, 10, 11, 13, 18]
Accepted clients: [15, 7, 0, 3, 9, 4, 6, 5, 10]
Validation accuracy: 0.9267
Communication cost (round / cumulative MB): 51.8794 / 1426.6833
Payment spent this round: 26882319922.7752
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 28/100
Selected clients: [15, 7, 0, 8, 3, 9, 4, 6, 5, 10, 1, 2, 11, 12, 13, 18]
Accepted clients: [15, 7, 8, 3, 9, 6, 5, 10]
Validation accuracy: 0.9267
Communication cost (round / cumulative MB): 51.8794 / 1478.5627
Payment spent this round: 27639568371.3041
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 29/100
Selected clients: [15, 7, 8, 3, 0, 9, 6, 5, 10, 1, 2, 4, 11, 12, 13, 18]
Accepted clients: [15, 7, 8, 3, 0, 9, 6, 5, 1, 4, 12]
Validation accuracy: 0.9293
Communication cost (round / cumulative MB): 51.8794 / 1530.4421
Payment spent this round: 32940307511.0062
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 30/100
Selected clients: [15, 7, 8, 3, 0, 9, 6, 5, 12, 1, 4, 2, 10, 11, 13, 18]
Accepted clients: [15, 8, 3, 0, 9, 12, 1, 10, 11]
Validation accuracy: 0.9265
Communication cost (round / cumulative MB): 51.8794 / 1582.3215
Payment spent this round: 26882319922.7752
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 31/100
Selected clients: [15, 8, 7, 3, 0, 9, 12, 1, 10, 11, 2, 4, 5, 6, 13, 18]
Accepted clients: [15, 8, 7, 0, 9, 1, 10, 11, 5, 6]
Validation accuracy: 0.9273
Communication cost (round / cumulative MB): 51.8794 / 1634.2009
Payment spent this round: 29532689492.6263
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 32/100
Selected clients: [15, 8, 7, 0, 3, 9, 1, 10, 11, 6, 5, 2, 4, 12, 13, 18]
Accepted clients: [15, 8, 7, 9, 11, 6]
Validation accuracy: 0.9240
Communication cost (round / cumulative MB): 51.8794 / 1686.0803
Payment spent this round: 26882319922.7752
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 33/100
Selected clients: [15, 8, 7, 9, 0, 3, 11, 6, 1, 2, 4, 5, 10, 12, 13, 18]
Accepted clients: [15, 8, 7, 9, 3, 11, 6, 5, 12, 13]
Validation accuracy: 0.9283
Communication cost (round / cumulative MB): 51.8794 / 1737.9597
Payment spent this round: 31804434838.2129
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 34/100
Selected clients: [15, 8, 7, 9, 3, 6, 11, 0, 12, 5, 13, 1, 2, 4, 10, 18]
Accepted clients: [15, 7, 9, 3, 11, 0, 12, 5, 1, 2]
Validation accuracy: 0.9260
Communication cost (round / cumulative MB): 51.8794 / 1789.8391
Payment spent this round: 29911313716.8907
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 35/100
Selected clients: [15, 7, 8, 9, 3, 11, 0, 12, 5, 1, 2, 4, 6, 10, 13, 18]
Accepted clients: [15, 7, 8, 9, 3, 0, 12, 5, 4, 10]
Validation accuracy: 0.9270
Communication cost (round / cumulative MB): 51.8794 / 1841.7185
Payment spent this round: 34833428632.3284
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 36/100
Selected clients: [15, 7, 8, 9, 3, 0, 12, 5, 10, 11, 4, 1, 2, 6, 13, 18]
Accepted clients: [15, 7, 8, 9, 3, 0, 12, 5, 11, 6]
Validation accuracy: 0.9285
Communication cost (round / cumulative MB): 51.8794 / 1893.5979
Payment spent this round: 38241046650.7084
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 37/100
Selected clients: [15, 7, 8, 9, 3, 0, 12, 5, 11, 6, 1, 2, 4, 10, 13, 18]
Accepted clients: [15, 7, 8, 3, 0, 12, 11, 2, 13]
Validation accuracy: 0.9223
Communication cost (round / cumulative MB): 51.8794 / 1945.4773
Payment spent this round: 34833428632.3284
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 38/100
Selected clients: [15, 7, 8, 3, 9, 0, 12, 11, 2, 13, 1, 4, 5, 6, 10, 18]
Accepted clients: [15, 7, 8, 3, 9, 12, 11, 2, 5]
Validation accuracy: 0.9260
Communication cost (round / cumulative MB): 51.8794 / 1997.3567
Payment spent this round: 38998295099.2373
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 39/100
Selected clients: [15, 7, 8, 3, 9, 12, 11, 0, 2, 5, 1, 4, 6, 10, 13, 18]
Accepted clients: [15, 7, 8, 3, 11, 0, 1, 6, 10]
Validation accuracy: 0.9273
Communication cost (round / cumulative MB): 51.8794 / 2049.2361
Payment spent this round: 35969301305.1217
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 40/100
Selected clients: [15, 7, 8, 3, 9, 11, 0, 12, 6, 1, 10, 2, 4, 5, 13, 18]
Accepted clients: [15, 8, 3, 9, 11, 0, 12, 10, 2, 4, 5]
Validation accuracy: 0.9270
Communication cost (round / cumulative MB): 51.8794 / 2101.1155
Payment spent this round: 32940307511.0062
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 41/100
Selected clients: [15, 8, 7, 3, 9, 0, 11, 12, 10, 5, 4, 2, 1, 6, 13, 18]
Accepted clients: [15, 8, 7, 3, 0, 12, 5, 2, 1, 6]
Validation accuracy: 0.9263
Communication cost (round / cumulative MB): 51.8794 / 2152.9949
Payment spent this round: 38241046650.7084
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 42/100
Selected clients: [15, 8, 7, 3, 0, 12, 9, 5, 11, 2, 6, 1, 4, 10, 13, 18]
Accepted clients: [15, 8, 7, 3, 0, 12, 9, 5, 10]
Validation accuracy: 0.9273
Communication cost (round / cumulative MB): 51.8794 / 2204.8743
Payment spent this round: 42027288893.3528
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 43/100
Selected clients: [15, 8, 7, 3, 0, 12, 9, 5, 10, 1, 2, 4, 6, 11, 13, 18]
Accepted clients: [15, 8, 7, 3, 0, 12, 9, 10, 2, 6, 11, 18]
Validation accuracy: 0.9247
Communication cost (round / cumulative MB): 51.8794 / 2256.7537
Payment spent this round: 44299034238.9394
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 44/100
Selected clients: [15, 8, 7, 3, 0, 12, 9, 10, 18, 6, 11, 2, 1, 4, 5, 13]
Accepted clients: [15, 8, 7, 3, 0, 9, 6, 11, 1, 4, 5]
Validation accuracy: 0.9277
Communication cost (round / cumulative MB): 51.8794 / 2308.6331
Payment spent this round: 45056282687.4683
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S2 | Clean Data + T-RAS | Round 45/100
Selected clients: [15, 8, 7, 3, 0, 9, 6, 12, 11, 1, 5, 4, 2, 10, 13, 18]
Accepted clients: [15, 8, 3, 9, 6, 12, 11, 10]

S3 | Dishonest Bidding + Vanilla FL:   0%|          | 0/100 [00:00<?, ?it/s]

------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 1/100
Selected clients: [8, 13, 5, 2, 6, 3, 17, 0, 16, 18, 7, 19, 12, 15]
Accepted clients: [8, 13, 5, 2, 6, 3, 17, 0, 16, 18, 7, 19, 12, 15]
Validation accuracy: 0.7542
Communication cost (round / cumulative MB): 45.3945 / 45.3945
Payment spent this round: 96.1435
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 2/100
Selected clients: [8, 14, 15, 10, 2, 12, 7, 9, 11, 19, 0]
Accepted clients: [8, 14, 15, 10, 2, 12, 7, 9, 11, 19, 0]
Validation accuracy: 0.8715
Communication cost (round / cumulative MB): 35.6671 / 81.0616
Payment spent this round: 99.5466
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 3/100
Selected clients: [16, 3, 10, 18, 17, 9, 6, 14, 11]
Accepted clients: [16, 3, 10, 18, 17, 9, 6, 14, 11]
Validation accuracy: 0.8792
Communication cost (round / cumulative MB): 29.1822 / 110.2437
Payment spent this round: 99.7716
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 4/100
Selected clients: [13, 15, 3, 19, 14, 16, 6, 10, 5, 17, 11]
Accepted clients: [13, 15, 3, 19, 14, 16, 6, 10, 5, 17, 11]
Validation accuracy: 0.8960
Communication cost (round / cumulative MB): 35.6671 / 145.9108
Payment spent this round: 97.5929
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 5/100
Selected clients: [1, 5, 16, 3, 18, 17, 7, 15, 19, 0, 9]
Accepted clients: [1, 5, 16, 3, 18, 17, 7, 15, 19, 0, 9]
Validation accuracy: 0.9140
Communication cost (round / cumulative MB): 35.6671 / 181.5779
Payment spent this round: 96.6762
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 6/100
Selected clients: [18, 0, 8, 13, 5, 19, 16, 3, 7, 1, 14]
Accepted clients: [18, 0, 8, 13, 5, 19, 16, 3, 7, 1, 14]
Validation accuracy: 0.9005
Communication cost (round / cumulative MB): 35.6671 / 217.2450
Payment spent this round: 96.4626
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 7/100
Selected clients: [14, 6, 7, 1, 9, 5, 16, 19, 4, 18, 15]
Accepted clients: [14, 6, 7, 1, 9, 5, 16, 19, 4, 18, 15]
Validation accuracy: 0.9140
Communication cost (round / cumulative MB): 35.6671 / 252.9120
Payment spent this round: 99.6006
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 8/100
Selected clients: [9, 4, 6, 10, 0, 2, 16, 14, 17, 13, 8]
Accepted clients: [9, 4, 6, 10, 0, 2, 16, 14, 17, 13, 8]
Validation accuracy: 0.8895
Communication cost (round / cumulative MB): 35.6671 / 288.5791
Payment spent this round: 99.8753
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 9/100
Selected clients: [0, 10, 1, 14, 2, 9, 11, 18, 8]
Accepted clients: [0, 10, 1, 14, 2, 9, 11, 18, 8]
Validation accuracy: 0.8948
Communication cost (round / cumulative MB): 29.1822 / 317.7613
Payment spent this round: 99.3596
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 10/100
Selected clients: [9, 4, 18, 3, 10, 13, 19, 7, 5, 17]
Accepted clients: [9, 4, 18, 3, 10, 13, 19, 7, 5, 17]
Validation accuracy: 0.9187
Communication cost (round / cumulative MB): 32.4246 / 350.1859
Payment spent this round: 96.6607
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 11/100
Selected clients: [4, 12, 3, 18, 1, 13, 10, 2, 0, 7, 8]
Accepted clients: [4, 12, 3, 18, 1, 13, 10, 2, 0, 7, 8]
Validation accuracy: 0.9137
Communication cost (round / cumulative MB): 35.6671 / 385.8530
Payment spent this round: 99.1994
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 12/100
Selected clients: [19, 8, 2, 10, 0, 1, 16, 11, 12, 5, 13, 3]
Accepted clients: [19, 8, 2, 10, 0, 1, 16, 11, 12, 5, 13, 3]
Validation accuracy: 0.9223
Communication cost (round / cumulative MB): 38.9095 / 424.7625
Payment spent this round: 97.8712
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 13/100
Selected clients: [0, 14, 10, 13, 16, 12, 3, 18, 8, 7, 5]
Accepted clients: [0, 14, 10, 13, 16, 12, 3, 18, 8, 7, 5]
Validation accuracy: 0.8988
Communication cost (round / cumulative MB): 35.6671 / 460.4296
Payment spent this round: 99.7678
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 14/100
Selected clients: [10, 4, 18, 7, 14, 13, 2, 19, 5, 1]
Accepted clients: [10, 4, 18, 7, 14, 13, 2, 19, 5, 1]
Validation accuracy: 0.8740
Communication cost (round / cumulative MB): 32.4246 / 492.8542
Payment spent this round: 96.5082
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 15/100
Selected clients: [13, 19, 8, 14, 9, 18, 3, 5, 2, 17]
Accepted clients: [13, 19, 8, 14, 9, 18, 3, 5, 2, 17]
Validation accuracy: 0.9093
Communication cost (round / cumulative MB): 32.4246 / 525.2789
Payment spent this round: 97.6237
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 16/100
Selected clients: [8, 14, 15, 11, 0, 9, 2, 12, 13, 10]
Accepted clients: [8, 14, 15, 11, 0, 9, 2, 12, 13, 10]
Validation accuracy: 0.9193
Communication cost (round / cumulative MB): 32.4246 / 557.7035
Payment spent this round: 96.5939
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 17/100
Selected clients: [5, 1, 8, 18, 17, 6, 3, 19, 12, 9, 16, 11]
Accepted clients: [5, 1, 8, 18, 17, 6, 3, 19, 12, 9, 16, 11]
Validation accuracy: 0.9275
Communication cost (round / cumulative MB): 38.9095 / 596.6130
Payment spent this round: 99.1575
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 18/100
Selected clients: [14, 6, 17, 11, 18, 10, 3, 16, 2, 0, 8]
Accepted clients: [14, 6, 17, 11, 18, 10, 3, 16, 2, 0, 8]
Validation accuracy: 0.9147
Communication cost (round / cumulative MB): 35.6671 / 632.2801
Payment spent this round: 99.9902
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 19/100
Selected clients: [14, 1, 16, 2, 9, 3, 19, 8, 13, 0]
Accepted clients: [14, 1, 16, 2, 9, 3, 19, 8, 13, 0]
Validation accuracy: 0.9230
Communication cost (round / cumulative MB): 32.4246 / 664.7047
Payment spent this round: 99.7024
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 20/100
Selected clients: [6, 15, 3, 16, 1, 12, 13, 0, 9, 11, 8, 17]
Accepted clients: [6, 15, 3, 16, 1, 12, 13, 0, 9, 11, 8, 17]
Validation accuracy: 0.9310
Communication cost (round / cumulative MB): 38.9095 / 703.6143
Payment spent this round: 99.5440
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 21/100
Selected clients: [17, 7, 16, 12, 2, 5, 0, 4, 3, 18, 13, 11, 6, 8]
Accepted clients: [17, 7, 16, 12, 2, 5, 0, 4, 3, 18, 13, 11, 6, 8]
Validation accuracy: 0.9277
Communication cost (round / cumulative MB): 45.3945 / 749.0088
Payment spent this round: 98.7362
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 22/100
Selected clients: [9, 7, 5, 14, 16, 8, 13, 19, 1, 2, 17]
Accepted clients: [9, 7, 5, 14, 16, 8, 13, 19, 1, 2, 17]
Validation accuracy: 0.9267
Communication cost (round / cumulative MB): 35.6671 / 784.6758
Payment spent this round: 95.9786
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 23/100
Selected clients: [17, 1, 10, 2, 11, 4, 0, 3, 6, 5, 12, 19]
Accepted clients: [17, 1, 10, 2, 11, 4, 0, 3, 6, 5, 12, 19]
Validation accuracy: 0.9270
Communication cost (round / cumulative MB): 38.9095 / 823.5854
Payment spent this round: 99.0215
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 24/100
Selected clients: [5, 6, 3, 11, 0, 10, 17, 18, 19, 16, 1, 8]
Accepted clients: [5, 6, 3, 11, 0, 10, 17, 18, 19, 16, 1, 8]
Validation accuracy: 0.9293
Communication cost (round / cumulative MB): 38.9095 / 862.4949
Payment spent this round: 97.6596
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 25/100
Selected clients: [10, 12, 8, 11, 19, 1, 5, 0, 18, 16, 15, 7, 6]
Accepted clients: [10, 12, 8, 11, 19, 1, 5, 0, 18, 16, 15, 7, 6]
Validation accuracy: 0.9297
Communication cost (round / cumulative MB): 42.1520 / 904.6469
Payment spent this round: 94.7616
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 26/100
Selected clients: [17, 6, 2, 9, 0, 15, 1, 12, 8, 19, 5, 10]
Accepted clients: [17, 6, 2, 9, 0, 15, 1, 12, 8, 19, 5, 10]
Validation accuracy: 0.9313
Communication cost (round / cumulative MB): 38.9095 / 943.5565
Payment spent this round: 97.8311
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 27/100
Selected clients: [14, 19, 0, 18, 16, 4, 15, 9, 10, 7]
Accepted clients: [14, 19, 0, 18, 16, 4, 15, 9, 10, 7]
Validation accuracy: 0.9223
Communication cost (round / cumulative MB): 32.4246 / 975.9811
Payment spent this round: 97.2239
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 28/100
Selected clients: [15, 0, 12, 16, 13, 8, 7, 6, 19, 18, 11, 10, 2, 5]
Accepted clients: [15, 0, 12, 16, 13, 8, 7, 6, 19, 18, 11, 10, 2, 5]
Validation accuracy: 0.9267
Communication cost (round / cumulative MB): 45.3945 / 1021.3756
Payment spent this round: 97.1918
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 29/100
Selected clients: [9, 5, 2, 7, 6, 19, 11, 17, 18, 14, 15, 8]
Accepted clients: [9, 5, 2, 7, 6, 19, 11, 17, 18, 14, 15, 8]
Validation accuracy: 0.9295
Communication cost (round / cumulative MB): 38.9095 / 1060.2851
Payment spent this round: 99.2329
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 30/100
Selected clients: [12, 4, 8, 7, 0, 13, 1, 6, 3, 18, 19, 15, 16]
Accepted clients: [12, 4, 8, 7, 0, 13, 1, 6, 3, 18, 19, 15, 16]
Validation accuracy: 0.9300
Communication cost (round / cumulative MB): 42.1520 / 1102.4371
Payment spent this round: 97.2466
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 31/100
Selected clients: [12, 13, 11, 2, 17, 0, 10, 18, 19, 6, 14, 7]
Accepted clients: [12, 13, 11, 2, 17, 0, 10, 18, 19, 6, 14, 7]
Validation accuracy: 0.9105
Communication cost (round / cumulative MB): 38.9095 / 1141.3467
Payment spent this round: 99.3116
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 32/100
Selected clients: [0, 18, 6, 9, 11, 14, 13, 8, 7, 1, 16]
Accepted clients: [0, 18, 6, 9, 11, 14, 13, 8, 7, 1, 16]
Validation accuracy: 0.9233
Communication cost (round / cumulative MB): 35.6671 / 1177.0138
Payment spent this round: 99.7772
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 33/100
Selected clients: [4, 3, 9, 6, 0, 2, 17, 15, 5, 7, 16, 8, 12]
Accepted clients: [4, 3, 9, 6, 0, 2, 17, 15, 5, 7, 16, 8, 12]
Validation accuracy: 0.9330
Communication cost (round / cumulative MB): 42.1520 / 1219.1658
Payment spent this round: 98.4593
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 34/100
Selected clients: [10, 13, 8, 1, 5, 2, 18, 17, 15, 7, 19, 4]
Accepted clients: [10, 13, 8, 1, 5, 2, 18, 17, 15, 7, 19, 4]
Validation accuracy: 0.9260
Communication cost (round / cumulative MB): 38.9095 / 1258.0753
Payment spent this round: 95.5699
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 35/100
Selected clients: [11, 18, 14, 0, 15, 5, 12, 2, 3, 19, 16, 4]
Accepted clients: [11, 18, 14, 0, 15, 5, 12, 2, 3, 19, 16, 4]
Validation accuracy: 0.9155
Communication cost (round / cumulative MB): 38.9095 / 1296.9849
Payment spent this round: 99.5086
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 36/100
Selected clients: [17, 5, 11, 1, 15, 4, 16, 7, 18, 19, 12, 2, 0, 13]
Accepted clients: [17, 5, 11, 1, 15, 4, 16, 7, 18, 19, 12, 2, 0, 13]
Validation accuracy: 0.9307
Communication cost (round / cumulative MB): 45.3945 / 1342.3793
Payment spent this round: 98.6812
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 37/100
Selected clients: [19, 6, 8, 10, 18, 12, 9, 0, 16, 1, 2, 17]
Accepted clients: [19, 6, 8, 10, 18, 12, 9, 0, 16, 1, 2, 17]
Validation accuracy: 0.9215
Communication cost (round / cumulative MB): 38.9095 / 1381.2889
Payment spent this round: 99.7429
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 38/100
Selected clients: [9, 2, 15, 1, 7, 10, 4, 3, 16, 19]
Accepted clients: [9, 2, 15, 1, 7, 10, 4, 3, 16, 19]
Validation accuracy: 0.9270
Communication cost (round / cumulative MB): 32.4246 / 1413.7135
Payment spent this round: 99.8757
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 39/100
Selected clients: [4, 8, 3, 1, 6, 17, 11, 5, 18, 9, 7]
Accepted clients: [4, 8, 3, 1, 6, 17, 11, 5, 18, 9, 7]
Validation accuracy: 0.9310
Communication cost (round / cumulative MB): 35.6671 / 1449.3806
Payment spent this round: 97.8530
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 40/100
Selected clients: [8, 18, 3, 14, 1, 17, 11, 7, 6, 0, 13]
Accepted clients: [8, 18, 3, 14, 1, 17, 11, 7, 6, 0, 13]
Validation accuracy: 0.9280
Communication cost (round / cumulative MB): 35.6671 / 1485.0477
Payment spent this round: 99.1014
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 41/100
Selected clients: [5, 9, 8, 7, 19, 13, 6, 1, 16, 17, 11, 3]
Accepted clients: [5, 9, 8, 7, 19, 13, 6, 1, 16, 17, 11, 3]
Validation accuracy: 0.9317
Communication cost (round / cumulative MB): 38.9095 / 1523.9572
Payment spent this round: 97.8200
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 42/100
Selected clients: [18, 16, 6, 17, 19, 14, 11, 4, 2, 5, 8, 12, 7, 13]
Accepted clients: [18, 16, 6, 17, 19, 14, 11, 4, 2, 5, 8, 12, 7, 13]
Validation accuracy: 0.9093
Communication cost (round / cumulative MB): 45.3945 / 1569.3517
Payment spent this round: 99.9446
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 43/100
Selected clients: [0, 1, 2, 14, 4, 11, 8, 17, 16, 18, 5, 13]
Accepted clients: [0, 1, 2, 14, 4, 11, 8, 17, 16, 18, 5, 13]
Validation accuracy: 0.8982
Communication cost (round / cumulative MB): 38.9095 / 1608.2612
Payment spent this round: 97.7433
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 44/100
Selected clients: [7, 12, 15, 16, 5, 3, 9, 13, 1, 6, 4]
Accepted clients: [7, 12, 15, 16, 5, 3, 9, 13, 1, 6, 4]
Validation accuracy: 0.9327
Communication cost (round / cumulative MB): 35.6671 / 1643.9283
Payment spent this round: 95.8710
Hackers caught this round: 0
------------------------------------------------------------------------------------------------------------------------
S3 | Dishonest Bidding + Vanilla FL | Round 45/100
Selected clients: [9, 19, 18, 11, 7, 16, 2, 0, 14, 1, 8]
Accepted clients: [9, 19, 18, 11, 7, 16, 2, 0, 14, 1, 8]
Validation accuracy: 0.9210
Communication cost (round / cumulative MB): 35.6671 / 1679.5954
Payment spent this round: 99.3097

In [ ]:
print('Detailed client table for scenario S4 - Dishonest Bidding + T-RAS')
display(scenario_results['S4']['client_summary_df'])

print('Detailed client table for scenario S6 - Hacker Poisoning + T-RAS')
display(scenario_results['S6']['client_summary_df'])

In [ ]:
palette = {
    'S1': '#1f77b4',
    'S2': '#ff7f0e',
    'S3': '#2ca02c',
    'S4': '#d62728',
    'S5': '#9467bd',
    'S6': '#8c564b',
}


def build_metrics_dataframe(results: Dict[str, Dict[str, Any]]) -> pd.DataFrame:
    rows = []
    for scenario_id, result in results.items():
        scenario = result['scenario']
        rows.append(
            {
                'Scenario ID': scenario_id,
                'Scenario Label': result['scenario_label'],
                'Case': scenario.case_name,
                'Mechanism': scenario.mechanism,
                'Final Accuracy': result['final_accuracy'],
                'Best Accuracy': result['best_accuracy'],
                'Convergence Round': result['convergence_round'],
                'Total Communication (MB)': result['total_communication_mb'],
                'Total Spending': result['total_spending'],
                'Avg Selected Clients': float(np.mean(result['selected_counts'])),
                'Avg Accepted Clients': float(np.mean(result['accepted_counts'])),
                'Blocked Attackers': result['extra_stats_total'].get('blocked_attackers', 0.0),
            }
        )
    return pd.DataFrame(rows).sort_values('Scenario ID').reset_index(drop=True)


metrics_df = build_metrics_dataframe(scenario_results)
display(metrics_df)

# ======================================================
# Figure 1: Accuracy curve and cumulative communication
# ======================================================
fig, axes = plt.subplots(1, 2, figsize=(18, 6))
rounds = np.arange(1, cfg.GLOBAL_ROUNDS + 1)
for scenario_id, result in scenario_results.items():
    axes[0].plot(rounds, result['accuracy_history'], label=scenario_id, color=palette[scenario_id], linewidth=2)
    axes[1].plot(rounds, result['cumulative_communication_history_mb'], label=scenario_id, color=palette[scenario_id], linewidth=2)

axes[0].set_title('Accuracy across 100 rounds for all six scenarios')
axes[0].set_xlabel('Round')
axes[0].set_ylabel('Validation Accuracy')
axes[0].legend()
axes[0].grid(True, linestyle='--', alpha=0.5)

axes[1].set_title('Cumulative communication cost across 100 rounds')
axes[1].set_xlabel('Round')
axes[1].set_ylabel('Communication (MB)')
axes[1].legend()
axes[1].grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# ======================================================
# Figure 2: Bar charts for key metrics
# ======================================================
fig, axes = plt.subplots(1, 3, figsize=(22, 6))
sns.barplot(data=metrics_df, x='Scenario ID', y='Final Accuracy', palette=palette, ax=axes[0])
sns.barplot(data=metrics_df, x='Scenario ID', y='Convergence Round', palette=palette, ax=axes[1])
sns.barplot(data=metrics_df, x='Scenario ID', y='Total Communication (MB)', palette=palette, ax=axes[2])
axes[0].set_title('Final Accuracy')
axes[1].set_title('Convergence Round')
axes[2].set_title('Total Communication Cost (MB)')
for axis in axes:
    axis.grid(True, linestyle='--', alpha=0.4)
plt.tight_layout()
plt.show()

# ======================================================
# Figure 3: Heatmap of normalized metrics
# ======================================================
heatmap_df = metrics_df.set_index('Scenario ID')[
    ['Final Accuracy', 'Best Accuracy', 'Convergence Round', 'Total Communication (MB)', 'Total Spending']
].copy()
normalized_df = heatmap_df.copy()
for column in normalized_df.columns:
    column_values = normalized_df[column].astype(float)
    if column in {'Convergence Round', 'Total Communication (MB)', 'Total Spending'}:
        normalized_df[column] = 1.0 - (column_values - column_values.min()) / max(column_values.max() - column_values.min(), 1e-8)
    else:
        normalized_df[column] = (column_values - column_values.min()) / max(column_values.max() - column_values.min(), 1e-8)

plt.figure(figsize=(10, 6))
sns.heatmap(normalized_df, annot=heatmap_df.round(4), fmt='', cmap='YlGnBu', cbar_kws={'label': 'Normalized Score'})
plt.title('Metric matrix: raw values and normalized scores')
plt.ylabel('Scenario')
plt.xlabel('Metric')
plt.tight_layout()
plt.show()

# ======================================================
# Figure 4: Scatter plot of final accuracy vs communication
# ======================================================
plt.figure(figsize=(9, 6))
for _, row in metrics_df.iterrows():
    marker = 'o' if row['Mechanism'] == 'Vanilla FL' else 's'
    plt.scatter(
        row['Total Communication (MB)'],
        row['Final Accuracy'],
        s=220,
        marker=marker,
        color=palette[row['Scenario ID']],
        alpha=0.85,
    )
    plt.text(
        row['Total Communication (MB)'] + 0.01,
        row['Final Accuracy'] + 0.001,
        row['Scenario ID'],
        fontsize=10,
    )
plt.title('Scatter plot: Final Accuracy vs Communication Cost')
plt.xlabel('Total Communication (MB)')
plt.ylabel('Final Accuracy')
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()

# ======================================================
# Figure 5: Bid histogram and Shapley histogram
# ======================================================
fig, axes = plt.subplots(1, 2, figsize=(18, 6))
axes[0].hist(
    scenario_results['S3']['client_summary_df']['Reported Bid'],
    bins=10,
    alpha=0.65,
    label='S3 - Vanilla FL',
    color=palette['S3'],
)
axes[0].hist(
    scenario_results['S4']['client_summary_df']['Reported Bid'],
    bins=10,
    alpha=0.65,
    label='S4 - T-RAS',
    color=palette['S4'],
)
axes[0].set_title('Histogram of reported bids in the dishonest bidding case')
axes[0].set_xlabel('Reported Bid')
axes[0].set_ylabel('Frequency')
axes[0].legend()
axes[0].grid(True, linestyle='--', alpha=0.5)

for scenario_id in ['S2', 'S4', 'S6']:
    shapley_values = list(scenario_results[scenario_id]['last_shapley_scores'].values())
    if shapley_values:
        axes[1].hist(shapley_values, bins=10, alpha=0.55, label=scenario_id, color=palette[scenario_id])
axes[1].set_title('Histogram of final-round Shapley values in T-RAS scenarios')
axes[1].set_xlabel('Shapley Value')
axes[1].set_ylabel('Frequency')
axes[1].legend()
axes[1].grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# ======================================================
# Figure 6: S6 pie chart and client-class heatmap
# ======================================================
fig, axes = plt.subplots(1, 2, figsize=(18, 7))
s6_breakdown = scenario_results['S6']['extra_stats_total']
pie_labels = [
    'Clean accepted',
    'Hackers blocked',
    'Clean blocked',
    'Hackers accepted',
]
pie_values = [
    s6_breakdown.get('accepted_clean', 0.0),
    s6_breakdown.get('blocked_attackers', 0.0),
    s6_breakdown.get('blocked_clean', 0.0),
    s6_breakdown.get('accepted_attackers', 0.0),
]
non_zero_pairs = [(label, value) for label, value in zip(pie_labels, pie_values) if value > 0]
axes[0].pie(
    [pair[1] for pair in non_zero_pairs],
    labels=[pair[0] for pair in non_zero_pairs],
    autopct='%1.1f%%',
    startangle=90,
)
axes[0].set_title('Scenario S6: accepted vs blocked updates')

sns.heatmap(client_class_matrix, cmap='mako', ax=axes[1])
axes[1].set_title('Non-IID client-class distribution heatmap')
axes[1].set_xlabel('Class ID')
axes[1].set_ylabel('Client ID')
plt.tight_layout()
plt.show()

# ======================================================
# Figure 7: Confusion matrix for the best scenario
# ======================================================
best_scenario_id = metrics_df.sort_values('Best Accuracy', ascending=False).iloc[0]['Scenario ID']
best_result = scenario_results[best_scenario_id]
plt.figure(figsize=(12, 10))
sns.heatmap(best_result['final_confusion_matrix'], cmap='crest', square=True)
plt.title(f"Confusion matrix for the best scenario: {best_scenario_id}")
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.tight_layout()
plt.show()

# ======================================================
# Figure 8: Reputation trace for S4 and S6
# ======================================================
fig, axes = plt.subplots(1, 2, figsize=(18, 6))
for axis, scenario_id in zip(axes, ['S4', 'S6']):
    result = scenario_results[scenario_id]
    tracked_clean_id = result['tracked_clean_id']
    tracked_attack_id = result['tracked_attack_id']
    reputation_rounds = np.arange(0, len(result['reputation_history'][tracked_clean_id]))

    axis.plot(
        reputation_rounds,
        result['reputation_history'][tracked_clean_id],
        label=f'Clean client #{tracked_clean_id}',
        linewidth=2,
        marker='o',
    )
    if tracked_attack_id is not None:
        axis.plot(
            reputation_rounds,
            result['reputation_history'][tracked_attack_id],
            label=f'Attack client #{tracked_attack_id}',
            linewidth=2,
            marker='o',
        )
    axis.set_title(f'Reputation trace - {scenario_id}')
    axis.set_xlabel('Round (0 = before training)')
    axis.set_ylabel('Reputation')
    axis.legend()
    axis.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# ======================================================
# Figure 9: Client selection frequency in S6
# ======================================================
s6_client_df = scenario_results['S6']['client_summary_df'].copy()
plt.figure(figsize=(12, 6))
sns.barplot(data=s6_client_df, x='Client ID', y='Selected Rounds', hue='Type')
plt.title('Client selection frequency in scenario S6')
plt.xlabel('Client ID')
plt.ylabel('Selected Rounds')
plt.grid(True, linestyle='--', alpha=0.4)
plt.tight_layout()
plt.show()